Repository BLSQ/iaso, pull requests merged in 2023-04, with the labels that each got.

#497 WC-201: Worflow follow up condition not displayed
  hat/assets/js/apps/Iaso/domains/workflows/components/followUps/Table.tsx
Labels: release

#494 WC2-179 Fix calculate types can't be mapped to calculate types
  iaso/api/workflows/serializers.py
Labels: bug, release

#480 POLIO-921 update comment on campaigns fields
  plugins/polio/api.py
  plugins/polio/models.py
  plugins/polio/serializers.py
Labels: documentation

#498 WC2-179 - Calculate fields should not be tied to a type.
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/TargetCell.tsx
  iaso/api/workflows/serializers.py
  iaso/tests/api/workflows/test_workflows_changes.py
  iaso/tests/fixtures/form_test_workflow.xlsx
Labels: enhancement

#506 WC2-202: Workflow change improvements
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/ActionCell.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/HeadSourceCell.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/HeadTargetCell.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/MappingTable.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/Modal.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/SourceCell.tsx
  hat/assets/js/apps/Iaso/domains/workflows/config/changes.tsx
  hat/assets/js/apps/Iaso/domains/workflows/details.tsx
  hat/assets/js/apps/Iaso/domains/workflows/messages.ts
Labels: release

#472 IA-1983: registry
  hat/assets/js/apps/Iaso/components/maps/MapLegend.tsx
  hat/assets/js/apps/Iaso/components/maps/tools/ClusterSwitchLegend.tsx
  hat/assets/js/apps/Iaso/constants/menu.js
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/urls.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/components/ActionTableColumnComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/ColumnSelect.tsx
  hat/assets/js/apps/Iaso/domains/instances/config.js
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitForm.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitInfos.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.js
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgUnit.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgunitTypes.ts
  hat/assets/js/apps/Iaso/domains/registry/components/ActionCell.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MapPopUp.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitInfos.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
  hat/assets/js/apps/Iaso/domains/registry/details.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetEnketoUrl.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetForms.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetInstances.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnit.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnitType.ts
  hat/assets/js/apps/Iaso/domains/registry/index.tsx
  hat/assets/js/apps/Iaso/domains/registry/messages.ts
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/types/table.ts
  hat/assets/js/apps/Iaso/utils/mapUtils.ts
  hat/menupermissions/migrations/0045_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/api/instances.py
  iaso/api/org_units.py
Labels: release

#514 WC2-204: Workflows change: order versions by creation date
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/Modal.tsx
  hat/assets/js/apps/Iaso/domains/workflows/messages.ts
Labels: release

#521 POLIO-948-949: update RA status logic + hide dg auth and ag/nopv group fields
  plugins/polio/js/src/forms/RiskAssessmentForm.js
Labels: release

#513 WC2-196/ WC2-197: Workflows follow-ups - current date and current date time, calculate operators
  hat/assets/js/apps/Iaso/domains/forms/fields/constants.ts
  hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetQueryBuildersFields.ts
  hat/assets/js/apps/Iaso/domains/instances/utils/jsonLogicParse.ts
  hat/assets/js/apps/Iaso/domains/workflows/components/followUps/ActionCell.tsx
  hat/assets/js/apps/Iaso/domains/workflows/components/followUps/Modal.tsx
  hat/assets/js/apps/Iaso/domains/workflows/config/followUps.tsx
  hat/assets/js/apps/Iaso/domains/workflows/details.tsx
  package-lock.json
Labels: release

#526 IA-2067: make tooltip text visible
  hat/assets/js/apps/Iaso/domains/instances/components/SpeedDialInstanceActions.js
Labels: release

#532 IA-2076: Completeness stats permissions issues
  hat/assets/js/apps/Iaso/domains/completenessStats/CompletenessStatsFilters.tsx
  iaso/api/groups.py
Labels: release

#538 Ia 2068 json data store
  hat/menupermissions/migrations/0046_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/admin.py
  iaso/api/data_store.py
  iaso/api/permissions.py
  iaso/migrations/0200_jsondatastore.py
  iaso/migrations/0201_alter_jsondatastore_content.py
  iaso/migrations/0202_auto_20230419_1444.py
  iaso/models/data_store.py
  iaso/tests/api/test_json_data_store.py
  iaso/urls.py
Labels: release

#534 POLIO-969: Add the % target population in the SIA calendar Excel extract
  plugins/polio/api.py
  plugins/polio/export_utils.py
Labels: release

#544 POLIO-2080, POLIO-2081, POLIO-2082: update bulk user csv template
  iaso/api/fixtures/sample_bulk_user_creation.csv
Labels: release

#533 POLIO-973: add read-only endpoint for configs
  plugins/polio/admin.py
  plugins/polio/api.py
  plugins/polio/migrations/0128_config_users.py
  plugins/polio/models.py
  plugins/polio/serializers.py
  plugins/polio/tests/test_json_configs.py
Labels: release

#542 IA-2073: add breadcrumbs to registry
  hat/assets/js/apps/Iaso/domains/orgUnits/components/LinkToOrgUnit.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/breadcrumbs/OrgUnitBreadcrumbs.tsx
  hat/assets/js/apps/Iaso/domains/registry/details.tsx
Labels: release

#545 IA-2094: User columns in Forms submissions
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/constants.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
Labels: release

#549 IA-2100: Adding doc for registry
  docs/pages/dev/how_to/create_registry_in_web_ui/create_registry_in_web_ui.md
Labels: release
