Repository BLSQ/iaso, pull requests merged in 2023-06, with the labels that each got.

#620 IA-1465 / IA-2180: Planning allow parent picking on list view
  hat/assets/js/apps/Iaso/domains/assignments/components/AssignmentsFilters.tsx
  hat/assets/js/apps/Iaso/domains/assignments/components/AssignmentsListTab.tsx
  hat/assets/js/apps/Iaso/domains/assignments/components/AssignmentsMapTab.tsx
  hat/assets/js/apps/Iaso/domains/assignments/components/AssignmentsSidebar.tsx
  hat/assets/js/apps/Iaso/domains/assignments/components/ParentDialog.tsx
  hat/assets/js/apps/Iaso/domains/assignments/hooks/useGetAssignmentData.ts
  hat/assets/js/apps/Iaso/domains/assignments/index.tsx
  hat/assets/js/apps/Iaso/domains/assignments/types/orgUnit.ts
Labels: release

#609 IA-2153: Make the difference between allowed-to-create children types and children-type to show in Iaso
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/components/OrgUnitsTypesDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useGetOrgUnitTypesDropdownOptions.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgunitTypes.ts
  iaso/api/org_unit_types/serializers.py
  iaso/migrations/0207_orgunittype_allow_creating_sub_unit_types.py
  iaso/migrations/0209_merge_20230602_1002.py
  iaso/models/org_unit.py
  iaso/tests/api/test_org_unit_types.py
Labels: release

#630 IA-2119 filter users with no type assigned
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  hat/assets/js/apps/Iaso/domains/users/index.js
  hat/assets/js/apps/Iaso/domains/users/messages.js
  iaso/api/profiles.py
Labels: release

#635 IA-2202 front end gps push bulk
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/index.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsMultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TableList.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useBulkSaveOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/messages.js
Labels: release

#629 WC2-237 Add endpoint to do WFP login from the mobile app
  plugins/wfp_auth/pkce-code-flow.png
  plugins/wfp_auth/urls.py
  plugins/wfp_auth/views.py
Labels: release

#617 IA-2135 Populate instance.name when creating from enketo
  iaso/api/enketo.py
  iaso/models/base.py
Labels: release

#644 IA-2160: provide filter planning in submissions
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
  hat/assets/js/apps/Iaso/domains/instances/constants.js
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetInstances.tsx
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
  iaso/api/instance_filters.py
  iaso/models/base.py
  iaso/tests/api/test_instances.py
Labels: release

#645 IA-2322 Fix duplicate orgunit in registry missing submissions
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetEmptyInstanceOrgUnits.ts
  iaso/api/completeness_stats.py
Labels: release

#653 IA-2226: restore dependencies update
  package-lock.json
  package.json
Labels: release

#646 POLIO-1037 reasons delay tracking
  hat/assets/js/apps/Iaso/components/AlertModal/AlertModal.tsx
  hat/assets/js/apps/Iaso/components/AlertModal/CloseButton.tsx
  hat/assets/js/apps/Iaso/components/AlertModal/messages.ts
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/uiConstants.js
  hat/assets/js/apps/Iaso/constants/uiConstants.ts
  hat/assets/js/apps/Iaso/domains/app/components/InfoPopper.tsx
  plugins/polio/admin.py
  plugins/polio/api.py
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/Inputs/DateInput.js
  plugins/polio/js/src/components/Rounds/ReasonForDelayModal/ReasonForDelayModal.tsx
  plugins/polio/js/src/components/Rounds/ReasonForDelayModal/ReasonsForDelayButton.tsx
  plugins/polio/js/src/components/Rounds/ReasonForDelayModal/hooks/reasons.ts
  plugins/polio/js/src/components/Rounds/ReasonForDelayModal/validation.ts
  plugins/polio/js/src/components/Rounds/RoundDates/RoundDates.tsx
  plugins/polio/js/src/components/Rounds/RoundDatesHistory/RoundDatesHistoryModal/RoundDatesHistoryIconButton.tsx
  plugins/polio/js/src/components/Rounds/RoundDatesHistory/RoundDatesHistoryModal/RoundDatesHistoryModal.tsx
  plugins/polio/js/src/components/Rounds/RoundDatesHistory/RoundDatesHistoryTable.tsx
  plugins/polio/js/src/components/Rounds/RoundDatesHistory/hooks/config.tsx
  plugins/polio/js/src/components/Rounds/RoundDatesHistory/hooks/useGetRoundDatesHistory.ts
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/forms/RoundForm.js
  plugins/polio/js/src/forms/RoundForm.tsx
  plugins/polio/migrations/0130_rounddatehistoryentry.py
  plugins/polio/migrations/0131_auto_20230607_1436.py
  plugins/polio/migrations/0132_auto_20230607_1527.py
  plugins/polio/migrations/0133_alter_rounddatehistoryentry_round.py
  plugins/polio/migrations/0134_add_rounddatehistoryentrey_to_existing_campaigns.py
  plugins/polio/models.py
  plugins/polio/serializers.py
Labels: release

#651 WC2-226: Fix 500 when there is no `email` field in the response
  plugins/wfp_auth/views.py
Labels: bug

#661 POLIO-1065: LQAS/IM maps colors
  plugins/polio/js/src/pages/IM/constants.ts
Labels: release

#662 IA-2256, IA-2260, IA-2261:Fix failing cypress tests
  hat/assets/js/cypress/fixtures/entities/list-page-2.json
  hat/assets/js/cypress/fixtures/entities/list.json
  hat/assets/js/cypress/fixtures/misc/validationStatuses.json
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailLinksTab.spec.js
  hat/assets/js/cypress/integration/07 - entities/list.spec.js
Labels: release

#668 IA-1647: add missing translation use roles in permission dropdown
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/messages.js
Labels: release

#664 IA-2196: add clustering on registry map
  hat/assets/js/apps/Iaso/domains/registry/components/MapTooltip.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenMap.tsx
Labels: release

#665 IA-2251 fix form attachment not working in enketo prod
  iaso/api/enketo.py
  iaso/tests/api/test_forms_attachment.py
Labels: release

#671 IA-2259 Separate Version for orgunit type api with allow_creating_sub_unit_types
  hat/assets/js/apps/Iaso/domains/assignments/hooks/requests/useGetOrgUnitTypes.ts
  hat/assets/js/apps/Iaso/domains/dataSources/requests.js
  hat/assets/js/apps/Iaso/domains/instances/index.spec.js
  hat/assets/js/apps/Iaso/domains/links/index.spec.js
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks.js
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetOrgUnitTypes.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useDeleteOrgUnitType.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useGetOrgUnitTypes.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useGetOrgUnitTypesDropdownOptions.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useSaveOrgUnitType.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnitType.ts
  hat/assets/js/apps/Iaso/domains/users/index.spec.js
  hat/assets/js/apps/Iaso/utils/requests.js
  hat/assets/js/cypress/integration/02 - forms/details.spec.js
  hat/assets/js/cypress/integration/02 - forms/list.spec.js
  hat/assets/js/cypress/integration/08 - orgUnitTypes/list.spec.js
  hat/assets/js/cypress/integration/11 - submissions/list.spec.js
  hat/assets/js/cypress/integration/12 - datasources/list.spec.js
  hat/webpack.dev.js
  iaso/api/org_unit_types/serializers.py
  iaso/api/org_unit_types/viewsets.py
  iaso/migrations/0217_fill_allow_creating_sub_unit_types.py
  iaso/tests/api/test_org_unit_types_v2.py
  iaso/tests/test_api.py
  iaso/urls.py
Labels: release

#657 IA-2129: Adding Locust to stress test Iaso
  locust/README.md
  locust/compose.yml
  locust/instance.xml
  locust/locustfile.py
  requirements-dev.txt
Labels: enhancement, help wanted

#672 Polio 1076 date history bugs
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  plugins/polio/js/src/components/Rounds/ReasonForDelayModal/hooks/reasons.ts
  plugins/polio/serializers.py
Labels: release

#675 IA-2271: fix tests
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailChildrenTab.spec.js
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailInfosTab.spec.js
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailLinksTab.spec.js
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailMapTab.spec.js
  hat/assets/js/cypress/integration/08 - orgUnitTypes/list.spec.js
Labels: release

#686 POLIO-1081: Calendar vaccine colors
  plugins/polio/js/src/components/campaignCalendar/Styles.js
  plugins/polio/js/src/components/campaignCalendar/cells/RoundCell.js
  plugins/polio/js/src/components/campaignCalendar/map/CalendarMapPanesMerged.tsx
Labels: release

#632 IA-1944: Frontend - user roles management and changes to users page
  hat/assets/js/apps/Iaso/constants/menu.js
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/urls.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/components/UserRolesFilters.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/config.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useDeleteUserRole.ts
  hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useGetUserRoles.ts
  hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useSaveUserRole.ts
  hat/assets/js/apps/Iaso/domains/userRoles/index.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/messages.ts
  hat/assets/js/apps/Iaso/domains/userRoles/types/userRoles.ts
  hat/assets/js/apps/Iaso/domains/userRoles/validation.ts
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  hat/assets/js/apps/Iaso/domains/users/components/PermissionsSwitches.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
  hat/assets/js/apps/Iaso/domains/users/config.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useDeleteProfile.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetProfiles.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserRolesDropDown.ts
  hat/assets/js/apps/Iaso/domains/users/index.js
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/domains/users/types.ts
  iaso/api/permissions.py
  iaso/api/profiles.py
  iaso/migrations/0217_profile_user_roles.py
  iaso/migrations/0218_merge_20230627_1233.py
  iaso/models/base.py
  iaso/tests/api/test_profiles.py
Labels: release

#666 IA-2188: users / projects & bulk update
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/projects/hooks/requests.ts
  hat/assets/js/apps/Iaso/domains/tasks/config.js
  hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useGetUserRoles.ts
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersMultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
  hat/assets/js/apps/Iaso/domains/users/config.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useBulkSaveProfiles.ts
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetProfiles.js
  hat/assets/js/apps/Iaso/domains/users/index.js
  hat/assets/js/apps/Iaso/domains/users/index.spec.js
  hat/assets/js/apps/Iaso/domains/users/index.tsx
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/domains/users/types.ts
  hat/assets/js/cypress/fixtures/profiles/list.json
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/audit/models.py
  iaso/api/profiles.py
  iaso/api/tasks/create/profiles_bulk_update.py
  iaso/migrations/0216_profile_projects.py
  iaso/migrations/0217_merge_0216_merge_20230614_0839_0216_profile_projects.py
  iaso/migrations/0218_merge_20230621_0850.py
  iaso/migrations/0219_alter_profile_projects.py
  iaso/migrations/0220_merge_20230628_1038.py
  iaso/models/base.py
  iaso/tasks/profiles_bulk_update.py
  iaso/test.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/urls.py
  package.json
Labels: release

#682 WC2-245 cypress dupe details
  hat/assets/js/apps/Iaso/components/stars/StarsComponent.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateDetails.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateDetailsTableButtons.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateInfos.tsx
  hat/assets/js/cypress/fixtures/duplicates/details.json
  hat/assets/js/cypress/fixtures/duplicates/instances-a.json
  hat/assets/js/cypress/fixtures/duplicates/instances-b.json
  hat/assets/js/cypress/fixtures/duplicates/list-details.json
  hat/assets/js/cypress/integration/14 - duplicates/details.spec.js
  hat/assets/js/cypress/integration/14 - duplicates/list.spec.js
Labels: release
