Repository BLSQ/iaso, pull requests merged in 2023-05, with the labels that each got.

#564 IA-2122: Registry deep link fullscreen and show names
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitPaper.tsx
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
Labels: release

#560 POLIO-957-975: change text automatic campaign email + Stop sending automatic emails after the last round start date of the campaign
  plugins/polio/management/commands/test_send_email.py
  plugins/polio/tasks/weekly_email.py
Labels: release

#566 POLIO-954: add BackdropClickModal component
  hat/assets/js/apps/Iaso/components/dialogs/BackdropClickModal/BackdropClickModal.tsx
  hat/assets/js/apps/Iaso/components/dialogs/BackdropClickModal/messages.ts
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  plugins/polio/js/src/components/CreateEditDialog.js
Labels: release

#565 IA-2115: Org uit details fi to bounds
  hat/assets/js/apps/Iaso/domains/forms/components/OrgUnitTypeFilterComponent.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/SourcesFilterComponent.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMap/OrgUnitMap.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/fitToBounds.js
Labels: release

#553 POLIO-995: add budget step at start of workflow
  plugins/polio/js/src/constants/budget.ts
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/forms/BudgetForm.tsx
  plugins/polio/migrations/0129_campaign_ra_completed_at_wfeditable.py
  plugins/polio/models.py
  plugins/polio/serializers.py
Labels: release

#567 IA-2123 filter org unit status registry
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetInstances.tsx
  iaso/api/instances.py
  iaso/tests/api/test_instances.py
Labels: release

#559 POLIO-942: Implement filter by org unit groups on Campaigns, SIA calendar and Budget tool
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/GroupsDialog.js
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/messages.js
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetGroups.ts
  iaso/api/groups.py
  iaso/migrations/0203_group_to_display.py
  iaso/migrations/0204_rename_to_display_group_block_of_countries.py
  iaso/models/base.py
  plugins/polio/api.py
  plugins/polio/budget/api.py
  plugins/polio/js/config.js
  plugins/polio/js/src/components/campaignCalendar/Filters.js
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/hooks/useGetCampaigns.ts
  plugins/polio/js/src/pages/Budget/BudgetFilters.tsx
  plugins/polio/js/src/pages/Budget/hooks/api/useGetBudget.ts
  plugins/polio/js/src/pages/Calendar.js
Labels: release

#341 IA-1835 Add form version id to instance
  iaso/admin.py
  iaso/migrations/0198_instance_form_version.py
  iaso/models/base.py
  iaso/tests/api/test_instances.py
Labels: next

#413 IA-1790 open the form versions api in read access to any connected users
  iaso/api/form_versions.py
  iaso/api/forms.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/api/test_form_versions_readonly.py
Labels: next

#573 POLIO-1003: Frontend: remove surge data from preparedness tab
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/campaignHistory/config.tsx
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/forms/PreparednessForm.js
  plugins/polio/js/src/hooks/useGetPreparednessData.js
Labels: release

#578 IA-2141: missing submissions is wrong
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/instances/hooks/requests/useDeleteInstance.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/ActionCell.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MissingInstanceButton.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MissingInstanceDialog.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetEmptyInstanceOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
  iaso/api/completeness_stats.py
Labels: release

#583 POLIO-1007 fix preparedness in weekly email
  plugins/polio/management/commands/test_send_email.py
  plugins/polio/tasks/weekly_email.py
Labels: release

#584 IA2-2090: Completeness stats dead cells should not be sortable
  package-lock.json
Labels: release

#556 IA-947: save precision and altitude in submission details + add info in csv/xlsx export
  hat/assets/js/apps/Iaso/components/maps/MarkerMapComponent.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsLocation.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsLocation.tsx
  hat/assets/js/apps/Iaso/domains/instances/constants.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/instances/types/instance.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitSourceRefDisplay.js
  hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
  iaso/api/instances.py
  iaso/models/base.py
Labels: release

#581 Ia 2136 dhsi2 mappings exlude versions from deleted forms
  hat/assets/js/apps/Iaso/domains/mappings/components/CreateMappingVersionDialogComponent.js
  hat/assets/js/apps/Iaso/domains/mappings/components/IasoSearchComponent.js
  iaso/api/form_versions.py
Labels: release

#580 IA-2078: from completeness stats table link back to ou linked submissions
  hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useCompletenessStatsColumns.tsx
  hat/assets/js/apps/Iaso/domains/completenessStats/messages.ts
  hat/assets/js/apps/Iaso/domains/completenessStats/types.ts
Labels: release

#582 POLIO-977: show districts without location in scope
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitLocationIcon.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/Inputs/ScopeField.tsx
  plugins/polio/js/src/components/Inputs/ScopeInput.tsx
  plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
  plugins/polio/js/src/components/Scopes/MapScope.tsx
  plugins/polio/js/src/components/Scopes/TablePlaceHolder.tsx
  plugins/polio/js/src/components/Scopes/types.ts
  plugins/polio/js/src/components/Scopes/utils.ts
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/forms/ScopeForm.tsx
  plugins/polio/js/src/hooks/useGetGeoJson.ts
  plugins/polio/js/src/hooks/useGetParentOrgUnit.ts
  plugins/polio/js/src/styles/theme.js
Labels: release

#594 POLIO-1019: fix missing translations risk assessment tab
  plugins/polio/js/src/hooks/useFormValidator.js
Labels: release

#588 IA-2139: add orgunit status filter in completeness stats
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/completenessStats/CompletenessStatsFilters.tsx
  hat/assets/js/apps/Iaso/domains/completenessStats/hooks/api/useGetCompletnessStats.ts
  hat/assets/js/apps/Iaso/domains/completenessStats/messages.ts
  hat/assets/js/apps/Iaso/domains/completenessStats/types.ts
Labels: release

#589 POLIO-1011 fix group dropdown in campaigns page
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetGroups.ts
  iaso/api/groups.py
  plugins/polio/js/config.js
  plugins/polio/js/src/components/campaignCalendar/Filters.js
  plugins/polio/js/src/constants/app.ts
  plugins/polio/js/src/pages/Budget/BudgetFilters.tsx
Labels: release

#602 WC2-194: link beneficiary page to duplicates page
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/entities/config.tsx
  hat/assets/js/apps/Iaso/domains/entities/details.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/hooks/api/useGetDuplicates.ts
  hat/assets/js/apps/Iaso/domains/entities/messages.ts
  hat/assets/js/apps/Iaso/domains/entities/types/beneficiary.ts
  iaso/api/deduplication/entity.py
  iaso/api/entity.py
Labels: release

#603 Add unit test for Limit downloads to root
  iaso/tests/api/test_mobile_orgunits.py
Labels: release

#607 Wc2 232 entities return 502 on coda dev environment
  iaso/api/mobile/entity.py
  iaso/api/mobile/entity_type.py
  iaso/models/entity.py
  iaso/tests/api/test_entities.py
Labels: release

#606 IA-2157: Add attachments to forms
  iaso/admin.py
  iaso/api/form_attachments.py
  iaso/api/forms.py
  iaso/migrations/0207_formattachment.py
  iaso/models/__init__.py
  iaso/models/forms.py
  iaso/tests/api/test_forms_attachment.py
  iaso/urls.py
Labels: enhancement, release

#618 POLIO-1034: move percentage of target population from risk assessment tab to rounds tab
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/forms/RiskAssessmentForm.js
  plugins/polio/js/src/forms/RoundForm.js
  plugins/polio/js/src/forms/RoundsForm.js
Labels: release

#621 WC2-226 Integrate WFP CIAM as am auth provider
  README.md
  docker-compose.yml
  hat/api/authentication.py
  hat/assets/js/apps/Iaso/components/errors/PageNoPerms.tsx
  hat/assets/js/apps/Iaso/components/errors/messages.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js
  hat/locale/fr/LC_MESSAGES/django.po
  hat/settings.py
  hat/templates/iaso/login.html
  hat/templates/iaso/pages/wfp_login.html
  hat/urls.py
  iaso/urls.py
  mypy.ini
  plugins/wfp_auth/README.md
  plugins/wfp_auth/__init__.py
  plugins/wfp_auth/provider.py
  plugins/wfp_auth/templates/wfp_auth/login_subtemplate.html
  plugins/wfp_auth/templates/wfp_auth/new_account_email.html
  plugins/wfp_auth/templates/wfp_auth/new_account_subject.txt
  plugins/wfp_auth/urls.py
  plugins/wfp_auth/views.py
  requirements.txt
Labels: release
