Repository BLSQ/iaso, pull requests merged in 2023-08, with the labels that each got.

#693 IA-2292 500 when using a csv with semicolon in batch user creation + add projects and user roles
  iaso/api/bulk_create_users.py
  iaso/api/fixtures/sample_bulk_user_creation.csv
  iaso/tests/fixtures/test_user_bulk_create_creator_no_access_to_ou.csv
  iaso/tests/fixtures/test_user_bulk_create_duplicated_ou_name.csv
  iaso/tests/fixtures/test_user_bulk_create_invalid_mail.csv
  iaso/tests/fixtures/test_user_bulk_create_invalid_orgunit.csv
  iaso/tests/fixtures/test_user_bulk_create_invalid_ou_name.csv
  iaso/tests/fixtures/test_user_bulk_create_invalid_password.csv
  iaso/tests/fixtures/test_user_bulk_create_no_mail.csv
  iaso/tests/fixtures/test_user_bulk_create_semicolon.csv
  iaso/tests/fixtures/test_user_bulk_create_user_access_to_child_ou.csv
  iaso/tests/fixtures/test_user_bulk_create_user_duplicate_ou_names.csv
  iaso/tests/fixtures/test_user_bulk_create_valid.csv
  iaso/tests/fixtures/test_user_bulk_create_valid_with_perm.csv
  iaso/tests/fixtures/test_user_bulk_create_valid_with_projects.csv
  iaso/tests/fixtures/test_user_bulk_create_valid_with_roles.csv
  iaso/tests/fixtures/test_user_bulk_missing_columns.csv
  iaso/tests/test_create_users_from_csv.py
Labels: release

#712 IA-2304: Filter instances by user ID
  hat/assets/js/apps/Iaso/components/forms/AsyncSelect.tsx
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
  hat/assets/js/apps/Iaso/domains/instances/constants.js
  hat/assets/js/apps/Iaso/domains/instances/hooks/requests/getUsersDropDown.tsx
  hat/assets/js/apps/Iaso/domains/instances/hooks/useGetProfilesDropdown.tsx
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/domains/teams/hooks/requests/useGetProfilesDropdown.ts
  hat/assets/js/cypress/fixtures/profiles/ids/69-999.json
  hat/assets/js/cypress/fixtures/profiles/search/lui.json
  hat/assets/js/cypress/fixtures/profiles/search/mario.json
  hat/assets/js/cypress/integration/11 - submissions/list.spec.js
  iaso/api/instance_filters.py
  iaso/api/profiles.py
  iaso/api/query_params.py
  iaso/models/base.py
  iaso/tests/api/test_instances.py
  iaso/tests/api/test_profiles.py
Labels: enhancement

#736 IA-2043: Create a new permission - limit data sources access to view only
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/urls.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceInfo.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/components/VersionsDialog.js
  hat/assets/js/apps/Iaso/domains/dataSources/config.js
  hat/assets/js/apps/Iaso/domains/dataSources/details.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/hooks/useGetDataSources.ts
  hat/assets/js/apps/Iaso/domains/dataSources/index.js
  hat/assets/js/apps/Iaso/domains/dataSources/messages.js
  hat/assets/js/apps/Iaso/domains/dataSources/requests.js
  hat/assets/js/apps/Iaso/domains/dataSources/types/dataSources.ts
  hat/assets/js/apps/Iaso/domains/dataSources/utils.js
  hat/assets/js/apps/Iaso/domains/userRoles/messages.ts
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/menupermissions/migrations/0051_alter_custompermissionsupport_options.py
  hat/menupermissions/migrations/0053_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/api/data_sources.py
  iaso/tests/api/test_data_sources.py
Labels: release

#755 HOTFIX: fix round history bug with round 0
  plugins/polio/js/src/components/Rounds/RoundDates/RoundDates.tsx
  plugins/polio/js/src/forms/RoundForm.tsx
  plugins/polio/serializers.py
Labels: release

#749 IA-2326: change duplicated instance wording
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/constants.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
Labels: release

#752 IA-2343: upgrade Bluesquare-component
  package-lock.json
Labels: release

#747 WC2-249 beneficiary types improvements
  hat/assets/js/apps/Iaso/constants/menu.js
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/domains/app/components/MenuItemComponent.js
  hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
  hat/assets/js/apps/Iaso/domains/app/index.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/entities/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/config.tsx
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/requests/entitiyTypes.ts
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/index.tsx
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/messages.ts
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/types/entityType.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/requests.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/useFiltersParams.ts
  hat/assets/js/apps/Iaso/domains/entities/index.tsx
  hat/assets/js/apps/Iaso/domains/forms/config/index.js
  hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/messages.ts
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetPermissionsDropdown.ts
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  hat/assets/js/apps/Iaso/domains/users/utils.js
  hat/assets/js/apps/Iaso/libs/apiHooks.ts
  hat/assets/js/apps/Iaso/utils/featureFlags.js
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/assets/js/apps/Iaso/utils/usersUtils.ts
  hat/assets/js/cypress/integration/07 - entities/list.spec.js
  hat/assets/js/cypress/integration/07 - entities/types.spec.js
  hat/menupermissions/migrations/0053_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/api/entity.py
  iaso/migrations/0227_add_account_feature_flag_SHOW_BENEFICIARY_TYPES_IN_LIST_MENU.py
  iaso/tests/api/test_entity_types.py
Labels: release

#761 IA-2377: Fix issue in users management
  hat/assets/js/apps/Iaso/domains/users/components/PermissionsSwitches.tsx
  hat/menupermissions/models.py
  iaso/tasks/profiles_bulk_update.py
Labels: bug

#762 IA-2378: compare and fix translations
  hat/assets/js/apps/Iaso/components/filters/messages.js
  hat/assets/js/apps/Iaso/components/snackBars/messages.js
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/completeness/messages.js
  hat/assets/js/apps/Iaso/domains/completenessStats/messages.ts
  hat/assets/js/apps/Iaso/domains/dataSources/components/VersionsDialog.js
  hat/assets/js/apps/Iaso/domains/dataSources/messages.js
  hat/assets/js/apps/Iaso/domains/entities/duplicates/messages.ts
  hat/assets/js/apps/Iaso/domains/entities/messages.ts
  hat/assets/js/apps/Iaso/domains/forms/config/attachments.tsx
  hat/assets/js/apps/Iaso/domains/forms/hooks/useGetValidationStatus.ts
  hat/assets/js/apps/Iaso/domains/forms/messages.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/links/messages.js
  hat/assets/js/apps/Iaso/domains/orgUnits/messages.js
  hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/messages.ts
  hat/assets/js/apps/Iaso/domains/pages/messages.js
  hat/assets/js/apps/Iaso/domains/plannings/config.tsx
  hat/assets/js/apps/Iaso/domains/plannings/messages.ts
  hat/assets/js/apps/Iaso/domains/registry/messages.ts
  hat/assets/js/apps/Iaso/domains/storages/messages.ts
  hat/assets/js/apps/Iaso/domains/users/messages.js
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
Labels: release

#768 POLIO-1162: Fix LQAS Afro Map district view
  plugins/polio/api.py
  plugins/polio/helpers.py
Labels: release

#763 Polio 1141 refresh dashboard api
  hat/assets/js/apps/Iaso/domains/dataSources/components/AddTaskComponent.js
  hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
  iaso/test.py
  iaso/tests/api/test_task_dhis2_ou_importer.py
  plugins/polio/api.py
  plugins/polio/js/src/forms/PreparednessConfig.js
  plugins/polio/js/src/forms/PreparednessForm.js
  plugins/polio/js/src/hooks/useGetPreparednessData.js
  plugins/polio/tasks/api/__init__.py
  plugins/polio/tasks/api/create_refresh_preparedness_data.py
  plugins/polio/tests/test_refresh_preparedness_data.py
Labels: release

#767 IA-1976: Enable personalized user guide per IASO account
  hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
  iaso/api/setup_account.py
  iaso/migrations/0228_account_user_manual_path.py
  iaso/migrations/0229_merge_20230829_1408.py
  iaso/models/base.py
Labels: release
