Repository BLSQ/iaso, pull requests merged in 2023-11, with the labels that each got.

#908 POLIO-1277 Add GPEI Coordinator to mailing list of vacc auth emails.
  plugins/polio/tasks/vaccine_authorizations_mail_alerts.py
  plugins/polio/tests/test_vaccine_authorizations.py
Labels: release

#910 Add vaccine field in the scope export
  plugins/polio/api/campaigns/campaigns.py
Labels: release

#907 IA-2507: HOTFIX prevent multiple clicks on button
  hat/assets/js/apps/Iaso/domains/forms/components/FormVersionsDialogComponent.js
Labels: release

#906 POLIO-1289 Edit content of automatic emails on Fridays
  plugins/polio/tasks/weekly_email.py
Labels: release

#889 IA-2487: Provide groups in `/api/mobile/orgUnits`
  iaso/api/mobile/groups.py
  iaso/api/mobile/org_units.py
  iaso/api/serializers.py
  iaso/tests/api/test_mobile_orgunits.py
Labels: enhancement, release

#904 POLIO-1275 [Line-list] Polio notifications import backend
  iaso/models/org_unit.py
  iaso/tests/models/test_org_unit.py
  plugins/polio/admin.py
  plugins/polio/api/dashboards/forma.py
  plugins/polio/fixtures/linelist_template.xls
  plugins/polio/migrations/0152_notification_notificationimport.py
  plugins/polio/models.py
  plugins/polio/tests/fixtures/linelist_notification_invalid_format_test.txt
  plugins/polio/tests/fixtures/linelist_notification_test.xlsx
  plugins/polio/tests/fixtures/linelist_notification_wrong_cols_test.xlsx
  plugins/polio/tests/models/__init__.py
  plugins/polio/tests/models/test_notification_models.py
Labels: release

#927 Removing the limit to 1 year of history + improving performances of s…
  plugins/polio/api/dashboards/forma.py
  plugins/polio/models.py
Labels: release

#921 IA-2519 ensure formversion unicity for a given form
  iaso/migrations/0244_formversion_duplicate_version_id_for_same_form.py
  iaso/models/forms.py
Labels: release

#795 New APIs proposition
  docs/pages/dev/reference/API/org_unit_registry.md
  docs/pages/dev/reference/guidelines/git/git.md
Labels: documentation
