Repository BLSQ/iaso, pull requests merged in 2023-03, with the labels that each got.

#423 WC2-176 : Change frontend, backend, update tests
  hat/assets/js/apps/Iaso/domains/workflows/components/changes/Modal.tsx
  hat/assets/js/cypress/fixtures/workflows/details.json
  hat/assets/js/cypress/integration/13 - workflows/details.spec.js
  iaso/api/workflows/serializers.py
  iaso/tests/api/workflows/test_workflows_changes.py
Labels: release

#412 Add more tests to Storage passwords API
  iaso/tests/api/test_mobile_storage_password.py
Labels: enhancement, release

#424 POLIO-867 Fix preparedness data cron not refreshing
  .ebextensions/70_crontab.config
Labels: release

#432 Polio 874 remove email alert if no data
  plugins/polio/preparedness/warning_email.py
Labels: release

#409 Polio-827: Excel calendar export: Add target population, type of vaccine and whether it is and NID (Nationwide) or sNID (subNational)
  plugins/polio/api.py
  plugins/polio/export_utils.py
  plugins/polio/tests/test_base.py
Labels: release

#439 WC2-179: entities clean up and cypress list tests
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/entities/beneficiaries/components/Dialog.tsx
  hat/assets/js/apps/Iaso/domains/entities/beneficiaries/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/BeneficiaryBaseInfo.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/ListMap.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/Popup.tsx
  hat/assets/js/apps/Iaso/domains/entities/components/VisitDetails.tsx
  hat/assets/js/apps/Iaso/domains/entities/config.tsx
  hat/assets/js/apps/Iaso/domains/entities/details.tsx
  hat/assets/js/apps/Iaso/domains/entities/hooks/requests.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/requests/entities.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/useFiltersParams.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/useGetFieldValue.ts
  hat/assets/js/apps/Iaso/domains/entities/hooks/useGetFields.ts
  hat/assets/js/apps/Iaso/domains/entities/index.tsx
  hat/assets/js/apps/Iaso/domains/entities/types/beneficiary.ts
  hat/assets/js/apps/Iaso/domains/entities/types/entity.ts
  hat/assets/js/apps/Iaso/domains/entities/types/fields.ts
  hat/assets/js/apps/Iaso/domains/entities/types/filters.ts
  hat/assets/js/apps/Iaso/domains/entities/types/paginatedEntities.ts
  hat/assets/js/cypress/fixtures/entities/empty.json
  hat/assets/js/cypress/fixtures/entities/list-page-2.json
  hat/assets/js/cypress/fixtures/entities/list.json
  hat/assets/js/cypress/fixtures/profiles/list-not-paginated.json
  hat/assets/js/cypress/fixtures/teams/list.json
  hat/assets/js/cypress/integration/07 - entities/list.spec.js
  hat/assets/js/cypress/integration/13 - workflows/list.spec.js
  hat/assets/js/cypress/support/testPagination.js
Labels: release

#434 IA-1905 preparedness google sheets alerts send 4 emails
  .ebextensions/70_crontab.config
  beanstalk_worker/urls.py
  beanstalk_worker/views.py
  cron.yaml
  hat/settings.py
  hat/urls.py
  iaso/tests/test_task_launcher.py
  iaso/views.py
  plugins/polio/management/commands/refresh_preparedness_data.py
  plugins/polio/migrations/0123_make_polio_cron_task_user.py
  plugins/polio/tasks/__init__.py
  plugins/polio/tasks/refresh_preparedness_data.py
Labels: release

#435 IA-1326 Fix issue with EMPTY GEOM
  iaso/gpkg/import_gpkg.py
  iaso/models/org_unit.py
  iaso/tests/models/test_org_unit.py
Labels: release

#425 Allow pagination of mobile OrgUnit API
  iaso/api/mobile/entity.py
  iaso/api/mobile/org_units.py
  iaso/api/query_params.py
  iaso/tests/api/test_mobile_orgunits.py
Labels: enhancement

#442 WC2-172 deduplication front end(part1)
  hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.js
  hat/assets/js/apps/Iaso/components/snackBars/messages.js
  hat/assets/js/apps/Iaso/components/stars/StarsComponent.js
  hat/assets/js/apps/Iaso/components/stars/StarsComponent.tsx
  hat/assets/js/apps/Iaso/constants/menu.js
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/snackBars.js
  hat/assets/js/apps/Iaso/constants/urls.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/completenessStats/hooks/api/useGetFormsOptions.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateDetails.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateDetailsTableButtons.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateInfos.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateInfosTable.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/hooks/useDuplicateInfos.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/hooks/useDuplicationDetailsColumns.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/hooks/useEntityCell.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/hooks/api/useGetDuplicates.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/hooks/api/useIgnoreDuplicate.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/hooks/api/useMergeDuplicate.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/DuplicateCell.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/Duplicates.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/DuplicatesFilters.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/useDuplicationTableColumns.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/messages.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/mockDuplicationData.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/types.ts
  hat/assets/js/apps/Iaso/domains/entities/entityTypes/index.tsx
  hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/domains/links/config.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.js
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/hooks/useArrayState.spec.js
  hat/assets/js/apps/Iaso/hooks/useArrayState.ts
  hat/assets/js/apps/Iaso/hooks/useFilterState.ts
  hat/assets/js/apps/Iaso/hooks/useObjectState.spec.js
  hat/assets/js/apps/Iaso/hooks/useObjectState.ts
  hat/assets/js/apps/Iaso/libs/apiHooks.ts
  hat/assets/js/apps/Iaso/routing/redirections.js
  hat/assets/js/apps/Iaso/types/general.ts
  hat/menupermissions/migrations/0044_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  package-lock.json
  package.json
Labels: release

#452 POLIO-869: use translation for statuses
  plugins/polio/js/src/components/campaignCalendar/popper/RoundPopper.js
Labels: release

#447 POLIO-816: Budget steps add http:// to links if missing
  plugins/polio/js/src/pages/Budget/hooks/api/useSaveBudgetStep.tsx
Labels: release

#445 POLIO-870 Campaign Data Emails Sent Four Times
  .ebextensions/70_crontab.config
  cron.yaml
  plugins/polio/management/__init__.py
  plugins/polio/management/commands/__init__.py
  plugins/polio/tasks/weekly_email.py
  plugins/polio/tests/test_base.py
Labels: release

#456 Add Predefined filters to forms
  iaso/admin.py
  iaso/api/forms.py
  iaso/migrations/0197_formpredefinedfilter.py
  iaso/models/__init__.py
  iaso/models/forms.py
Labels: release

#446 POLIO-830: connect budget tool with budget tab
  plugins/polio/budget/models.py
  plugins/polio/budget/serializers.py
  plugins/polio/budget/workflow.py
  plugins/polio/js/src/forms/BudgetForm.js
  plugins/polio/models.py
  plugins/polio/serializers.py
Labels: release

#449 Polio-856 budget email template for submitter team
  plugins/polio/budget/models.py
  plugins/polio/templates/submitter_email.html
  plugins/polio/templates/submitter_email.txt
Labels: release

#460 POLIO-899: add missing field to budget tab
  plugins/polio/js/src/constants/budget.ts
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/forms/BudgetForm.js
  plugins/polio/js/src/hooks/useFormValidator.js
  plugins/polio/migrations/0125_campaign_re_submitted_to_orpg_operations1_at_wfeditable.py
  plugins/polio/models.py
Labels: release

#461 IA-1990 Fix Botswana preparedness google sheet
  plugins/polio/preparedness/parser.py
Labels: release

#457 Part of POLIO-897 Preparedness refresh not completing
  plugins/polio/tasks/refresh_preparedness_data.py
Labels: release

#459 WC2-189: change traces_sample_rate value
  hat/settings.py
Labels: release

#455 IA-1984: Planning show org units without geo location
  hat/assets/js/apps/Iaso/domains/assignments/hooks/requests/useGetOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/assignments/hooks/requests/useSaveAssignment.ts
  hat/assets/js/apps/Iaso/domains/assignments/hooks/useGetAssignmentData.ts
  hat/assets/js/apps/Iaso/domains/assignments/index.tsx
  hat/assets/js/apps/Iaso/domains/assignments/types/locations.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgUnit.ts
Labels: release

#475 WC2-195: Workflow follow-ups, add greater_or_equal and less_or_equal operators
  hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetQueryBuildersFields.ts
  hat/assets/js/apps/Iaso/domains/workflows/config/followUps.tsx
  hat/assets/js/apps/Iaso/domains/workflows/details.tsx
Labels: release

#467 WC2-185: add submissions to Duplicates page
  hat/assets/js/apps/Iaso/components/papers/ErrorPaperComponent.tsx
  hat/assets/js/apps/Iaso/components/papers/WidgetPaperComponent.js
  hat/assets/js/apps/Iaso/domains/app/components/ExpandableItem.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/DuplicateDetails.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/hooks/useGetInstancesForEntity.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/submissions/NoSubmission.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/details/submissions/SubmissionsForEntity.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/messages.ts
  hat/assets/js/apps/Iaso/domains/instances/compare/components/InstanceDetail.tsx
  hat/assets/js/apps/Iaso/domains/instances/compare/components/InstanceDetailRaw.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/details.js
Labels: release

#471 Polio-839 export budget list as csv
  hat/settings.py
  iaso/api/common.py
  mypy.ini
  plugins/polio/api.py
  plugins/polio/budget/api.py
  plugins/polio/budget/serializers.py
  plugins/polio/budget/test.py
  plugins/polio/js/src/hooks/useGetCampaigns.ts
  plugins/polio/js/src/pages/Budget/index.tsx
  plugins/polio/serializers.py
Labels: release

#468 POLIO-871: translate campaign data automatic emails into FR and PT
  plugins/polio/management/commands/test_send_email.py
  plugins/polio/tasks/weekly_email.py
Labels: release

#476 POLIO-914: Fix for emails still being sent multiple times
  beanstalk_worker/views.py
  iaso/tests/test_task_launcher.py
Labels: release

#458 POLIO 661: campaign history UI improvements
  hat/assets/js/apps/Iaso/domains/app/components/ExpandableItem.tsx
  plugins/polio/js/src/components/campaignHistory/CampaignHistory.tsx
  plugins/polio/js/src/components/campaignHistory/CampaignLogDetail.tsx
  plugins/polio/js/src/components/campaignHistory/Head.tsx
  plugins/polio/js/src/components/campaignHistory/MultiRows.tsx
  plugins/polio/js/src/components/campaignHistory/Row.tsx
  plugins/polio/js/src/components/campaignHistory/config.tsx
  plugins/polio/js/src/components/campaignHistory/useGetMapLog.tsx
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/hooks/useGetCampaignFieldLabel.ts
  plugins/polio/js/src/hooks/useGetCampaignHistory.ts
Labels: release

#483 POLIO-912: make initial_org_unit required and refactor dialog tab to allow an icon
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/Inputs/OrgUnitsSelect.tsx
  plugins/polio/js/src/components/MainDialog/PolioDialogTab.tsx
  plugins/polio/js/src/components/MainDialog/PolioDialogTabs.tsx
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/forms/BaseInfoForm.js
  plugins/polio/js/src/hooks/useFormValidator.js
  plugins/polio/js/src/styles/theme.js
Labels: BRAZZA

#487 HOTFIX: remove duplicate http on links
  plugins/polio/js/src/pages/Budget/hooks/api/useSaveBudgetStep.tsx
Labels: BRAZZA

#482 POLIO-898: replace budget status input
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/Inputs/DateInput.js
  plugins/polio/js/src/components/Inputs/StatusField.js
  plugins/polio/js/src/forms/BudgetForm.js
Labels: BRAZZA

#490 POLIO-934 timeline widget bug
  plugins/polio/budget/serializers.py
  plugins/polio/fixtures/budget.yaml
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
  plugins/polio/js/src/pages/Budget/BudgetDetails/TimelineStepIcon.tsx
Labels: BRAZZA

#492 IA-2042 Polio weekly email relax precondition for campaign
  iaso/management/commands/dhis2_ou_importer.py
  plugins/polio/management/commands/test_send_email.py
  plugins/polio/tasks/weekly_email.py
Labels: BRAZZA

#491 POLIO-938: add boolean to use field order
  iaso/api/common.py
  plugins/polio/api.py
  plugins/polio/budget/api.py
Labels: BRAZZA

#485 POLIO-920 auto fill statuses
  plugins/polio/js/src/components/CreateEditDialog.js
  plugins/polio/js/src/components/Inputs/StatusField.js
  plugins/polio/js/src/components/Inputs/index.js
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/forms/BudgetForm.js
  plugins/polio/js/src/forms/DetectionForm.js
  plugins/polio/js/src/forms/RiskAssessmentForm.js
Labels: BRAZZA
