Repository BLSQ/iaso, pull requests merged in 2024-03, with the labels that each got.

#1154 POLIO-1443: Remove test campaigns from the Campaigns CSV extract
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/js/config.tsx
  plugins/polio/js/src/constants/messages.js
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.js
  plugins/polio/js/src/domains/Campaigns/hooks/api/useGetCampaigns.ts
  plugins/polio/tests/test_base.py
Labels: release

#1163 IA-2619 Add phone number to users profile
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
  hat/assets/js/apps/Iaso/domains/users/types.ts
  hat/assets/js/apps/Iaso/utils/usersUtils.ts
  hat/settings.py
  iaso/api/profiles.py
  iaso/migrations/0264_profile_phone_number.py
  iaso/models/base.py
  iaso/tests/api/test_profiles.py
  requirements.txt
Labels: release

#1173 IA-2772 Add a `unique=True` constraint on `OrgUnitChangeRequest.uuid`
  iaso/migrations/0264_data_delete_change_requests_duplicates_uuid.py
  iaso/migrations/0265_alter_orgunitchangerequest_uuid.py
  iaso/models/org_unit.py
Labels: release

#1175 Update index.md
  docs/index.md
Labels: release

#1160 IA-2642: Payments part 1
  docs/pages/dev/reference/API/payments/payments.md
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/constants/urls.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/PotentialPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/PotentialPaymentsFilter.tsx
  hat/assets/js/apps/Iaso/domains/payments/config/usePotentialPaymentColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useGetPotentialPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/messages.ts
  hat/assets/js/apps/Iaso/domains/payments/types.ts
  hat/assets/js/apps/Iaso/types/general.ts
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/menupermissions/migrations/0059_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/admin.py
  iaso/api/org_unit_change_requests/filters.py
  iaso/api/payments/filters.py
  iaso/api/payments/pagination.py
  iaso/api/payments/serializers.py
  iaso/api/payments/views.py
  iaso/migrations/0264_payment_potentialpayment.py
  iaso/migrations/0266_merge_20240311_1034.py
  iaso/models/__init__.py
  iaso/models/org_unit.py
  iaso/models/payments.py
  iaso/tests/api/org_unit_change_requests/test_filters.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/api/payments/__init__.py
  iaso/tests/api/payments/test_filters.py
  iaso/tests/api/payments/test_payments.py
  iaso/tests/models/test_payments.py
  iaso/urls.py
Labels: release

#1172 IA-2732: Trace back the Form submission that matches
  hat/assets/js/apps/Iaso/components/dialogs/ImageGalleryComponent.tsx
  hat/assets/js/apps/Iaso/components/dialogs/ImageGalleryLink.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFilesListComponent.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/PaginatedInstancesFiles.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
Labels: release

#1181 IA-2787 update menu logic to hide main menu entry if dev==true
  hat/assets/js/apps/Iaso/constants/menu.tsx
Labels: release

#1149 WC2-334 transfer from otp to tsfp not recorded in etl
  plugins/wfp/common.py
Labels: release

#1134 TRIA-117 Allow superuser to export mobile app setup for a user
  docker-compose.yml
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/tasks/components/TaskDetails.tsx
  hat/assets/js/apps/Iaso/domains/tasks/config.tsx
  hat/assets/js/apps/Iaso/domains/tasks/index.js
  hat/assets/js/apps/Iaso/domains/users/components/ExportMobileAppSetupDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/config.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useCreateExportMobileSetup.ts
  hat/assets/js/apps/Iaso/domains/users/index.tsx
  hat/assets/js/apps/Iaso/domains/users/messages.js
  hat/assets/js/apps/Iaso/hooks/taskMonitor.ts
  iaso/api/tasks/__init__.py
  iaso/api/tasks/create/export_mobile_setup.py
  iaso/tasks/export_mobile_app_setup_for_user.py
  iaso/tasks/utils/__init__.py
  iaso/tasks/utils/mobile_app_setup_api_calls.py
  iaso/tests/__init__.py
  iaso/tests/tasks/__init__.py
  iaso/tests/tasks/test_export_mobile_app_setup_for_user.py
  iaso/urls.py
  iaso/utils/encryption.py
  iaso/utils/iaso_api_client.py
  iaso/utils/s3_client.py
  requirements.txt
  setuper/setuper.py
Labels: release

#1169 POLIO-1500 create notion of campaign type(s) backend
  plugins/polio/admin.py
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/migrations/0168_auto_20240306_1327.py
  plugins/polio/migrations/0169_auto_20240306_1327.py
  plugins/polio/models.py
  plugins/polio/tests/test_api.py
  plugins/polio/tests/test_base.py
Labels: postrelease

#1189 IA-2794: Create migration for deep search feature flag
  iaso/migrations/0269_auto_20240314_1326.py
Labels: enhancement

#1171 POLIO-1409: Make campaing round date required again
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundDates/RoundDates.tsx
  plugins/polio/js/src/hooks/useFormValidator.js
Labels: postrelease

#1201 IA-2739: Add "User" filter on Completeness stats page
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/completenessStats/CompletenessStatsFilters.tsx
  hat/assets/js/apps/Iaso/domains/completenessStats/hooks/api/useGetCompletnessStats.ts
  hat/assets/js/apps/Iaso/domains/completenessStats/messages.ts
  iaso/api/completeness_stats.py
  iaso/tests/api/test_completeness_stats.py
Labels: release

#1211 IA-2811 Instance API should give a 404 if form_id is unknown, not a 500
  iaso/api/instance_filters.py
  iaso/tests/api/test_instances.py
Labels: release

#1212 POLIO-1524 calendar polio by default
  plugins/polio/js/config.tsx
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/domains/Campaigns/hooks/api/useGetCampaignTypes.ts
Labels: release

#1199 IA-1301: 401 unauthorize
  hat/assets/js/apps/Iaso/libs/Api.ts
  hat/settings.py
  hat/urls.py
  iaso/api/mobile/entity_type.py
  iaso/tests/api/deduplication/test_entities_deduplication.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests_mobile.py
  iaso/tests/api/payments/test_potential_payments.py
  iaso/tests/api/test_apps.py
  iaso/tests/api/test_comment.py
  iaso/tests/api/test_completeness.py
  iaso/tests/api/test_completeness_stats.py
  iaso/tests/api/test_data_sources.py
  iaso/tests/api/test_derived_instances.py
  iaso/tests/api/test_devices.py
  iaso/tests/api/test_dhis2_resources.py
  iaso/tests/api/test_enketo.py
  iaso/tests/api/test_exportrequests.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/api/test_forms.py
  iaso/tests/api/test_forms_attachment.py
  iaso/tests/api/test_groups.py
  iaso/tests/api/test_instances.py
  iaso/tests/api/test_json_data_store.py
  iaso/tests/api/test_mobile_storage_password.py
  iaso/tests/api/test_mobileforms.py
  iaso/tests/api/test_modules.py
  iaso/tests/api/test_org_unit_types.py
  iaso/tests/api/test_org_unit_types_v2.py
  iaso/tests/api/test_org_units_bulk_update.py
  iaso/tests/api/test_pages.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/tests/api/test_projects.py
  iaso/tests/api/test_reports.py
  iaso/tests/api/test_storage.py
  iaso/tests/api/test_token.py
  iaso/tests/api/workflows/test_import_export.py
  iaso/tests/api/workflows/test_workflows.py
  iaso/tests/api/workflows/test_workflows_changes.py
  iaso/tests/api/workflows/test_workflows_followups.py
  iaso/tests/api/workflows/test_workflows_patch.py
  iaso/tests/test_json_configs.py
  iaso/tests/test_microplanning.py
  iaso/tests/test_multi_tenant.py
  plugins/polio/tests/api/test_notifications.py
  plugins/polio/tests/test_api.py
  plugins/polio/tests/test_lqas_country.py
Labels: release

#1203 IA-2779: improve payment audit
  .eslintrc.json
  hat/assets/js/apps/Iaso/components/Buttons/EditIconButton.tsx
  hat/assets/js/apps/Iaso/components/Buttons/RefreshButton.tsx
  hat/assets/js/apps/Iaso/components/tables/SimpleTableWithDeepLink.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditPaymentsDialog.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentLotDialog.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/PaymentLotActionCell.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentLotsColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentStatus.ts
  hat/assets/js/apps/Iaso/domains/payments/messages.ts
  hat/assets/js/apps/Iaso/domains/payments/types.ts
  hat/assets/js/apps/Iaso/domains/tasks/types.ts
  hat/audit/admin.py
  hat/audit/audit_logger.py
  hat/audit/models.py
  iaso/admin.py
  iaso/api/logs.py
  iaso/api/org_unit_change_requests/serializers.py
  iaso/api/payments/serializers.py
  iaso/api/payments/views.py
  iaso/api/tasks/create/payments_bulk_update.py
  iaso/migrations/0271_potentialpayment_payment_lot.py
  iaso/migrations/0272_paymentlot_task.py
  iaso/models/payments.py
  iaso/tasks/create_payments_from_payment_lot.py
  iaso/tasks/payments_bulk_update.py
  iaso/tests/api/payments/test_payment_lots.py
  iaso/tests/api/payments/test_payments.py
  iaso/tests/api/payments/test_payments_bulk_update.py
  iaso/tests/models/test_payments.py
Labels: postrelease

#1192 IA-2773: update payments api
  .eslintrc.json
  hat/assets/js/apps/Iaso/components/Buttons/EditIconButton.tsx
  hat/assets/js/apps/Iaso/components/Buttons/RefreshButton.tsx
  hat/assets/js/apps/Iaso/components/tables/SimpleTableWithDeepLink.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditPaymentsDialog.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentDialog.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentLotDialog.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/PaymentLotActionCell.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentLotsColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentStatus.ts
  hat/assets/js/apps/Iaso/domains/payments/messages.ts
  hat/assets/js/apps/Iaso/domains/payments/types.ts
  hat/assets/js/apps/Iaso/domains/tasks/types.ts
  hat/audit/admin.py
  hat/audit/audit_logger.py
  hat/audit/models.py
  iaso/admin.py
  iaso/api/logs.py
  iaso/api/org_unit_change_requests/serializers.py
  iaso/api/payments/serializers.py
  iaso/api/payments/views.py
  iaso/api/tasks/create/payments_bulk_update.py
  iaso/migrations/0271_potentialpayment_payment_lot.py
  iaso/migrations/0272_paymentlot_task.py
  iaso/migrations/0273_merge_20240327_0931.py
  iaso/models/payments.py
  iaso/tasks/create_payments_from_payment_lot.py
  iaso/tasks/payments_bulk_update.py
  iaso/tests/api/payments/test_payment_lots.py
  iaso/tests/api/payments/test_payments.py
  iaso/tests/api/payments/test_payments_bulk_update.py
  iaso/tests/models/test_payments.py
  iaso/tests/tasks/task_api_test_case.py
  iaso/urls.py
Labels: postrelease
