Repository BLSQ/iaso, pull requests merged in 2024-05, with the labels that each got.

#1254 POLIO-1102: scope only valid org units
  plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
  plugins/polio/js/src/domains/Campaigns/Scope/Scopes/DistrictScopeTable.tsx
  plugins/polio/js/src/domains/Campaigns/Scope/Scopes/MapScope.tsx
  plugins/polio/js/src/domains/Campaigns/Scope/Scopes/types.ts
  plugins/polio/js/src/domains/Campaigns/Scope/hooks/useGetGeoJson.ts
Labels: release

#1276 TRIA-7 Small fixes
  README.md
  hat/assets/js/apps/Iaso/domains/app/components/messages.js
  hat/assets/js/apps/Iaso/domains/dataSources/messages.js
  iaso/api/completeness_stats.py
  iaso/models/forms.py
  iaso/models/org_unit.py
Labels: release

#1290 IA-2915: Add descriptions of mobile feature flags on hover
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectFeatureFlags.tsx
  hat/assets/js/apps/Iaso/domains/projects/messages.ts
Labels: release

#1282 IA-2854: Registry cluster switch
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/registry/components/MapSettings.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MapToggleFullscreen.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/messages.ts
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
Labels: release

#1277 TRIA-7 Plugin settings.py and Trypelim Python dependencies
  README.md
  hat/assets/js/apps/Iaso/domains/app/types.ts
  hat/assets/js/apps/Iaso/routing/useRedirections.tsx
  hat/settings.py
  plugins/plugin_settings.py.example
  requirements-dev.txt
  requirements.txt
Labels: release

#1308 IA-2971: fix cypress tests
  hat/assets/js/cypress/integration/01 - auth/login.spec.js
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/assets/js/cypress/integration/05 - orgUnits/reviewChanges/changeRequest.spec.js
  hat/assets/js/cypress/integration/07 - entities/list.spec.js
  hat/assets/js/cypress/integration/11 - submissions/list.spec.js
  hat/assets/js/cypress/integration/14 - duplicates/list.spec.js
  hat/assets/js/cypress/support/commands.js
  hat/assets/js/cypress/support/testPageFilters.js
Labels: release

#1303 IA-2926: Create submissions for beneficiary with different dates
  setuper/entities.py
Labels: release

#1305 POLIO-1536, POLIO-1539, POLIO-1547, POLIO-1549: budget process layout improvements
  hat/assets/js/apps/Iaso/components/forms/TextArea.tsx
  plugins/polio/js/src/domains/Budget/BudgetButtons.tsx
  plugins/polio/js/src/domains/Budget/BudgetDetails/BudgetDetails.tsx
  plugins/polio/js/src/domains/Budget/BudgetDetails/BudgetDetailsFilters.tsx
  plugins/polio/js/src/domains/Budget/BudgetFilters.tsx
  plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
  plugins/polio/js/src/domains/Budget/BudgetProcess/EditBudgetProcessModal.tsx
  plugins/polio/js/src/domains/Budget/CreateBudgetStep/CreateBudgetStep.tsx
  plugins/polio/js/src/domains/Budget/cards/BudgetCard.tsx
  plugins/polio/js/src/domains/Budget/index.tsx
Labels: release

#1307 POLIO-1548 Hide non-polio campaigns
  plugins/polio/budget/api.py
  plugins/polio/models.py
  plugins/polio/tests/api/test_budget.py
  plugins/polio/tests/models/test_campaign_models.py
Labels: release

#1273 IA-2907 New API endpoint for Org Unit Tree
  iaso/admin.py
  iaso/api/data_sources.py
  iaso/api/org_unit_tree/__init__.py
  iaso/api/org_unit_tree/filters.py
  iaso/api/org_unit_tree/pagination.py
  iaso/api/org_unit_tree/serializers.py
  iaso/api/org_unit_tree/views.py
  iaso/api/org_units.py
  iaso/api/profiles.py
  iaso/migrations/0280_datasource_tree_config_status_fields.py
  iaso/models/data_source.py
  iaso/tests/api/org_unit_tree/__init__.py
  iaso/tests/api/org_unit_tree/test_views.py
  iaso/tests/models/test_datasource.py
  iaso/urls.py
Labels: release

#1314 IA-2897 - Registry v3
  hat/assets/js/apps/Iaso/domains/instances/components/LinkToInstance.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/breadcrumbs/OrgUnitBreadcrumbs.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/LinkToRegistry.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MapPopUp.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MissingInstanceButton.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/MissingInstanceDialog.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenList.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitInstances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitPaper.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/Placeholder.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/MapLegend.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/MapSettings.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/MapToggleFullscreen.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/MapToggleTooltips.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/MapTooltip.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/OrgUnitChildrenLocations.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/OrgUnitChildrenMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/OrgUnitChildrenShapes.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/OrgUnitLocation.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/EmptyInstances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/InstanceTitle.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/OrgUnitTitle.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/index.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetEmptyInstanceOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetForms.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetInstances.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetLegendOptions.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnit.ts
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnitType.ts
  hat/assets/js/apps/Iaso/domains/registry/index.tsx
  hat/assets/js/apps/Iaso/domains/registry/types/index.ts
  hat/assets/js/apps/Iaso/utils/map/mapUtils.ts
Labels: postrelease

#1336 IA-3042: fix submissions perm in form table
  hat/assets/js/apps/Iaso/domains/forms/config/index.js
Labels: release

#1341 IA-3004: Display a QRCode in the project configuration popup
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectInfos.tsx
  iaso/api/projects/viewsets.py
  iaso/tests/api/test_projects.py
  requirements.txt
Labels: enhancement
