Repository BLSQ/iaso, pull requests merged in 2024-11, with the labels that each got.

#1760 IA-3594 Add a missing "Admin" translation
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
Labels: release

#1757 [IA-3631] Replaced `assertEquals` by `assertEqual`
  iaso/tests/api/payments/test_payments.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/api/test_mobile_bulkuploads.py
  iaso/tests/api/test_profile_logs.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/tests/api/test_token.py
  iaso/tests/tasks/test_export_mobile_app_setup_for_user.py
  iaso/tests/tasks/test_process_mobile_bulk_upload.py
  iaso/tests/test_create_users_from_csv.py
Labels: bug

#1747 IA-3612: fix duplicate PotentialPayments
  iaso/admin.py
  iaso/api/payments/views.py
  iaso/migrations/0305_alter_potentialpayment_user.py
  iaso/migrations/0308_merge_20241028_1145.py
  iaso/models/payments.py
  iaso/tests/api/payments/test_payment_lots.py
  iaso/tests/models/test_payments.py
Labels: release

#1761 IA-3609 Avoid `PermissionDenied` when `projects` is an empty list `[]`
  iaso/api/profiles/profiles.py
  iaso/tests/api/test_profiles.py
Labels: release, hotfix

#1752 [IA-3601] Force QR code refresh after app_id update
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectInfos.tsx
  hat/assets/js/apps/Iaso/domains/projects/hooks/requests/useGetProjectQRCode.ts
  hat/assets/js/apps/Iaso/domains/projects/index.tsx
  hat/assets/js/apps/Iaso/domains/projects/messages.ts
  hat/assets/js/apps/Iaso/libs/Api.ts
Labels: bug, release

#1768 IA-3607 fix payment disappearing after bulk update
  hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/PaymentLotActionCell.tsx
  iaso/api/payments/views.py
  iaso/tasks/payments_bulk_update.py
  iaso/tests/api/payments/test_payments_bulk_update.py
  iaso/tests/models/test_payments.py
Labels: release

#1743 A few small fixes and improvements
  iaso/admin.py
  iaso/api/instances.py
  iaso/models/entity.py
Labels: release

#1774 IA-3649: Can not create a new instance of a form on staging
  hat/assets/js/apps/Iaso/domains/instances/actions.js
Labels: release

#1770 IA-3643: Multiple Sentry integration
  docker-compose.yml
  hat/assets/js/apps/Iaso/domains/app/contexts/SentryProvider.tsx
  hat/assets/js/apps/Iaso/index.tsx
  hat/common/context_processors.py
  hat/settings.py
Labels: release

#1782 IA-3660: convert org unit id to int in validation
  iaso/api/profiles/profiles.py
Labels: release, hotfix

#1795 Update the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release

#1789 IA-3663: Fix cypress tests
  hat/assets/js/apps/Iaso/domains/orgUnits/details/Children/OrgUnitChildrenTable.tsx
  hat/assets/js/cypress/fixtures/orgunittypes/dropdown-dummy-sub-org-unit-type-list.json
  hat/assets/js/cypress/fixtures/orgunittypes/dropdown-list.json
  hat/assets/js/cypress/integration/02 - forms/list.spec.js
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/assets/js/cypress/integration/05 - orgUnits/changesConfiguration/changeRequestConfiguration.spec.js
  hat/assets/js/cypress/integration/05 - orgUnits/reviewChanges/changeRequest.spec.js
  hat/assets/js/cypress/integration/06 - orgUnits tabs/detailChildrenTab.spec.js
  hat/assets/js/cypress/integration/08 - orgUnitTypes/list.spec.js
  hat/assets/js/cypress/integration/11 - submissions/list.spec.js
  hat/assets/js/cypress/integration/16 - links/list.spec.js
Labels: release

#1797 IA-2600: handle zero in select dropdown
  package-lock.json
Labels: release

#1796 WC2-523: Show correct nfc cards count
  iaso/api/entity.py
  iaso/models/entity.py
Labels: release

#1781 IA-3656 Fix: Delete entity type API endpoint
  iaso/api/entity_types.py
Labels: release

#1799 POLIO-1731 Fix scope CSV download
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/tests/api/test_campaigns_views.py
Labels: release

#1787 IA-3619: Go from the Submissions screen on the web to the Request Change screen related to this Submission
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsChangeRequests.tsx
  hat/assets/js/apps/Iaso/domains/instances/details.tsx
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/instances/types/instance.ts
  iaso/models/base.py
  iaso/tests/api/test_instances.py
Labels: release

#1794 WC2-603_WC2-604: ETL debug page not showing first visit or shows exit date for ben not yet exited
  plugins/wfp/common.py
  plugins/wfp/management/commands/nigeria/Under5.py
  plugins/wfp/management/commands/south_sudan/Under5.py
Labels: release

#1800 IA-3674 Fix: allow a user with restricted `OrgUnitType` to edit other users
  iaso/api/profiles/profiles.py
  iaso/tests/api/test_profiles.py
Labels: release

#1813 [IA-3689] Fixed validated OrgUnitType count
  iaso/api/org_unit_types/serializers.py
  iaso/tests/api/test_org_unit_types_v2.py
Labels: bug

#1819 POLIO-1740: Snack bars not showing correct status in supplychain
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/utils.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/useSaveSupplyChainForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/utils.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/vrf.tsx
Labels: hotfix

#1824 IA-3713: fix perm validation for geo user w/o org unit
  iaso/api/profiles/profiles.py
  iaso/tests/api/test_profiles.py
Labels: hotfix

#1818 [IA-3701] Fixed Django warning
  iaso/api/payments/views.py
  iaso/migrations/0309_alter_potentialpayment_user.py
  iaso/models/payments.py
Labels: bug
