Repository BLSQ/iaso, pull requests merged in 2024-09, with the labels that each got.

#1592 IA-3379: Allow the mobile app to download all groups
  iaso/api/mobile/groups.py
  iaso/tests/api/test_mobile_groups.py
Labels: enhancement, release

#1593 Fix black in Docker doesn't use the configuration
  .pre-commit-config.yaml
  docker-compose.yml
Labels: enhancement, release

#1587 IA-3366 Use `docker compose` instead of `docker-compose`
  Makefile
  README.md
  docs/pages/dev/how_to/add_new_permission/add_new_permission.md
  docs/pages/dev/how_to/contribute/contribute.md
  docs/pages/dev/how_to/create_entities_in_web_ui/create_entities_in_web_ui.md
  docs/pages/dev/how_to/create_registry_in_web_ui/create_registry_in_web_ui.md
  docs/pages/dev/how_to/rebuild_front/rebuild_front.md
  docs/pages/dev/how_to/setup_dev_env/setup_dev_env.md
  docs/pages/dev/how_to/setup_dev_env/setuper.md
  docs/pages/dev/reference/docker/docker.md
  docs/pages/dev/reference/front-end_reference/front-end_reference.md
  docs/pages/dev/reference/guidelines/back-end/back-end.md
  hat/assets/README.rst
  hat/assets/js/cypress/README.md
  iaso/api/enketo.py
  iaso/enketo/README.md
  iaso/management/commands/fix_submissions_select_multiple.py
  iaso/management/commands/list_account_files.py
  iaso/management/commands/seed_test_data.py
  locust/README.md
  plugins/polio/README.md
  plugins/wfp/README.md
  setuper/README.md
Labels: release

#1606 IA-3338: Add fiter "Project" on Form statistics
  hat/assets/js/apps/Iaso/components/instancesGraph.tsx
  hat/assets/js/apps/Iaso/components/instancesTotalGraph.tsx
  hat/assets/js/apps/Iaso/constants/routes.tsx
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/forms/components/formStasts/Filters.tsx
  hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
  hat/assets/js/apps/Iaso/domains/forms/stats.js
  hat/assets/js/apps/Iaso/domains/forms/stats.tsx
  hat/assets/js/apps/Iaso/domains/forms/types/formStats.ts
  iaso/api/instances.py
  iaso/tests/api/test_instances.py
Labels: release

#1608 POLIO-1653 Fix for sorting not working on API for Vaccine Stock Management
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/VaccineStockVariation.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#1613 POLIO-1658 Order VARs and VRFs in reverse date order
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: release

#1611 IA-3401 enketo emoji support
  iaso/enketo/enketo_xml.py
  iaso/models/base.py
  iaso/tests/enketo/test_enketo_lib.py
  iaso/tests/fixtures/submission_with_emoji.xml
  iaso/tests/models/test_instance.py
  iaso/utils/emoji.py
Labels: release

#1598 IA-3355 add groupsets api
  hat/audit/models.py
  iaso/api/group_sets/__init__.py
  iaso/api/group_sets/filters.py
  iaso/api/group_sets/serializers.py
  iaso/api/group_sets/views.py
  iaso/migrations/0296_groupset_group_belonging.py
  iaso/models/base.py
  iaso/models/data_source.py
  iaso/tests/api/test_group_sets.py
  iaso/tests/api/test_profiles.py
  iaso/urls.py
Labels: postrelease

#1621 IA-3377: Fix Form accepts invalid parameter for periods
  iaso/api/forms.py
  iaso/tests/api/test_forms.py
  iaso/tests/api/test_mobileforms.py
Labels: bug

#1470 POLIO-1610: im refresh button
  iaso/api/tasks/__init__.py
  plugins/polio/api/urls.py
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/domains/LQAS-IM/shared/Filters.tsx
  plugins/polio/js/src/domains/LQAS-IM/shared/RefreshLqasIMData.tsx
  plugins/polio/js/src/domains/LQAS-IM/shared/hooks/api/useGetLqasImCountriesOptions.tsx
  plugins/polio/js/src/hooks/useGetLatestLQASIMUpdate.ts
  plugins/polio/tasks/api/refresh_im_data.py
  plugins/polio/tasks/api/refresh_lqas_data.py
  plugins/polio/tasks/api/refresh_lqas_im_data.py
  plugins/polio/tests/test_im_refresh_hh_data.py
  plugins/polio/tests/test_im_refresh_hh_ohh_data.py
  plugins/polio/tests/test_im_refresh_ohh_data.py
Labels: release

#1618 IA-3398 add warning when updating phone number
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/WarningModal/WarningModal.tsx
  hat/assets/js/apps/Iaso/domains/users/messages.ts
Labels: release

#1610 IA-3365 user history backend
  hat/audit/migrations/0005_alter_modification_user.py
  hat/audit/models.py
  iaso/api/instances.py
  iaso/api/profiles/audit.py
  iaso/api/profiles/bulk_create_users.py
  iaso/api/profiles/profiles.py
  iaso/api/tasks/create/profiles_bulk_update.py
  iaso/migrations/0297_merge_20240911_0935.py
  iaso/migrations/0297_merge_20240913_0900.py
  iaso/migrations/0298_merge_20240912_1428.py
  iaso/models/base.py
  iaso/tasks/profiles_bulk_update.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/tests/fixtures/test_user_bulk_create_all_fields.csv
  iaso/tests/test_create_users_from_csv.py
  iaso/urls.py
  iaso/utils/__init__.py
Labels: release

#1614 IA-3402 add user history api
  iaso/api/logs.py
  iaso/api/payments/serializers.py
  iaso/api/profiles/audit.py
  iaso/api/profiles/profile_logs.py
  iaso/tests/api/test_profile_logs.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/urls.py
Labels: release

#1629 IA-3387: Implement OUCRC list screen
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/routes.tsx
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/ConfirmDeleteModal.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Filter/OrgUnitChangeRequestConfigsFilter.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/OrgUnitChangeRequestConfigs.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Tables/OrgUnitChangeRequestConfigsTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/constants.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useDeleteOrgUnitChangeRequestConfig.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useGetOrgUnitChangeRequestConfigs.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/types.ts
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/assets/js/cypress/fixtures/orgunits/changes/configuration/empty.json
  hat/assets/js/cypress/fixtures/orgunits/changes/configuration/orgUnitChangeConfigurations-page2.json
  hat/assets/js/cypress/fixtures/orgunits/changes/configuration/orgUnitChangeConfigurations.json
  hat/assets/js/cypress/integration/05 - orgUnits/changesConfiguration/changeRequestConfiguration.spec.js
Labels: enhancement

#1599 [IA-3367] Prepare OUCRC model
  docs/pages/dev/reference/API/org_unit_change_request_configuration.md
  iaso/admin.py
  iaso/migrations/0296_orgunitchangerequestconfiguration.py
  iaso/migrations/0300_merge_20240916_1512.py
  iaso/models/__init__.py
  iaso/models/org_unit.py
  iaso/models/org_unit_change_request_configuration.py
  iaso/tests/models/test_org_unit_change_request_configuration.py
Labels: enhancement

#1641 [POLIO-1680] Allowing any user to download the scopes of the campaigns
  plugins/polio/js/src/domains/Calendar/Calendar.tsx
Labels: release

#1635 SANRUSSC24-23 Add delete project, fix delete accounts
  iaso/management/commands/delete_accounts.py
  iaso/management/commands/delete_project.py
Labels: release

#1643 IA-3438: Restricted project
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
Labels: release

#1638 POLIO-1662 Supply Chain: VRF & DG Approval include options of 'missing' and 'not required'
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/SupplyChainTabs.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineSupplyChainDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/validation.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
  plugins/polio/migrations/0197_vaccinerequestform_vrf_type_and_more.py
  plugins/polio/models/base.py
Labels: release

#1648 IA3451: History on OrgUnit doesn't work anymore on staging
  hat/assets/js/apps/Iaso/domains/users/history/UserHistoryLogDetails.tsx
  hat/assets/js/apps/Iaso/hooks/useGetLogDetails.tsx
Labels: release

#1612 [IA-3386] Prepare OUCRC API
  hat/audit/models.py
  iaso/api/org_unit_change_request_configurations/__init__.py
  iaso/api/org_unit_change_request_configurations/filters.py
  iaso/api/org_unit_change_request_configurations/pagination.py
  iaso/api/org_unit_change_request_configurations/serializers.py
  iaso/api/org_unit_change_request_configurations/views.py
  iaso/api/org_unit_change_request_configurations/views_mobile.py
  iaso/api/query_params.py
  iaso/models/org_unit_change_request_configuration.py
  iaso/tests/api/org_unit_change_request_configurations/__init__.py
  iaso/tests/api/org_unit_change_request_configurations/common_base_with_setup.py
  iaso/tests/api/org_unit_change_request_configurations/test_filters.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs_mobile.py
  iaso/tests/models/test_org_unit_change_request_configuration.py
  iaso/urls.py
Labels: enhancement

#1631 [IA-3389] Add OUCRC permissions
  hat/menupermissions/constants.py
  hat/menupermissions/migrations/0068_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/api/org_unit_change_request_configurations/permissions.py
  iaso/api/org_unit_change_request_configurations/serializers.py
  iaso/api/org_unit_change_request_configurations/validation.py
  iaso/api/org_unit_change_request_configurations/views.py
  iaso/api/org_unit_change_request_configurations/views_mobile.py
  iaso/models/org_unit_change_request_configuration.py
  iaso/tests/api/org_unit_change_request_configurations/common_base_with_setup.py
  iaso/tests/api/org_unit_change_request_configurations/test_filters.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs_mobile.py
Labels: enhancement

#1640 WC2-515: Integrate CIAM with multi-account setup
  plugins/wfp_auth/views.py
Labels: enhancement
