Repository BLSQ/iaso, pull requests merged in 2024-01, with the labels that each got.

#1024 IA-2597: update margin values for SetupAccount
  hat/assets/js/apps/Iaso/domains/setup/index.tsx
Labels: release

#1020 Polio-1393 remove link to budget procedure
  plugins/polio/js/src/domains/Budget/BudgetDetails/BudgetDetailsTableLayout.tsx
  plugins/polio/js/src/domains/Budget/BudgetDetails/LinkToProcedure.tsx
  plugins/polio/js/src/domains/Budget/BudgetDetails/mobile/BudgetDetailsFiltersMobile.tsx
  plugins/polio/js/src/domains/Budget/CreateBudgetStep/OverrideStepButton.tsx
Labels: release

#1008 IA-2573 Upgrade to Django 4.2
  beanstalk_worker/views.py
  hat/api_import/admin.py
  hat/audit/admin.py
  hat/dashboard/urls.py
  hat/settings.py
  hat/urls.py
  iaso/admin.py
  iaso/dhis2/derived_instance_generator.py
  iaso/migrations/0255_case_insensitive_collation.py
  iaso/migrations/0256_upgrade_to_django_4.py
  iaso/models/entity.py
  iaso/models/forms.py
  iaso/models/org_unit.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/api/test_forms.py
  iaso/tests/api/test_forms_attachment.py
  iaso/tests/api/test_instances.py
  iaso/tests/api/test_mappingversions.py
  iaso/tests/api/test_mobileforms.py
  iaso/tests/api/test_orgunits.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_storage.py
  iaso/tests/gpkg/test_export2.py
  iaso/tests/gpkg/test_import.py
  iaso/tests/models/test_org_unit_change_request.py
  iaso/tests/test_dhis2_ou_importer.py
  iaso/tests/test_microplanning.py
  iaso/utils/jsonlogic.py
  plugins/polio/admin.py
  plugins/polio/tests/api/test_notifications.py
  plugins/polio/tests/models/test_notification_models.py
  plugins/polio/tests/test_api.py
  plugins/test/admin.py
  plugins/wfp/admin.py
  requirements.txt
Labels: release

#1027 IA-2602: Fix GET /api/mobile/orgunits/changes/
  docs/pages/dev/reference/API/org_unit_registry.md
  iaso/api/org_unit_change_requests/serializers.py
  iaso/api/org_unit_change_requests/views_mobile.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests_mobile.py
  iaso/tests/api/org_unit_change_requests/test_serializers.py
Labels: bug

#1021 Polio 1358 vaccine module format thousand
  hat/assets/js/apps/Iaso/components/Cells/NumberCell.tsx
  hat/assets/js/apps/Iaso/components/forms/EditableTextFields.js
  hat/assets/js/apps/Iaso/components/forms/EditableTextFields.spec.js
  hat/assets/js/apps/Iaso/components/forms/InputComponent.tsx
  hat/assets/js/apps/Iaso/components/tables/PaperTableRow.tsx
  hat/assets/js/apps/Iaso/domains/app/constants.js
  hat/assets/js/apps/Iaso/hooks/useNumberSeparatorsFromLocale.tsx
  hat/assets/js/apps/Iaso/types/general.ts
  hat/assets/js/test/utils/redux.js
  plugins/polio/js/src/components/Inputs/NumberInput.tsx
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Budget/BudgetDetails/mobile/BudgetDetailsCardsLayout.tsx
  plugins/polio/js/src/domains/Campaigns/BaseInfo/BaseInfoForm.js
  plugins/polio/js/src/domains/Campaigns/Budget/BudgetForm.tsx
  plugins/polio/js/src/domains/Campaigns/RiskAssessment/RiskAssessmentForm.js
  plugins/polio/js/src/domains/Campaigns/Rounds/LqasDistrictsPassed/LqasDistrictsPassed.tsx
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundForm.tsx
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundsForm.js
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Table/useVaccineStockManagementDetailsColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditDestruction.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/useVaccineStockManagementTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/mocks/mockVaccineStockDetails.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Table/useVaccineSupplyChainTableColumns.tsx
  plugins/polio/js/src/styles/theme.js
Labels: release

#1038 IA-2462 Cypress submissions list
  .eslintrc.json
  hat/assets/js/cypress/integration/11 - submissions/list.spec.js
  hat/assets/js/cypress/support/commands.js
Labels: release

#1036 IA-2609: update link to user guide
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
Labels: release

#849 Setuper
  .gitignore
  setuper/README.md
  setuper/client.py
  setuper/data/entity-child_followup.xlsx
  setuper/data/entity-child_registration_2022090701.xlsx
  setuper/data/fosa1.jpeg
  setuper/data/fosa2.jpeg
  setuper/data/fosa3.jpeg
  setuper/data/persons.csv
  setuper/data/registry-population_commune.xlsx
  setuper/data/sample-credentials.py
  setuper/data/sample_form.xlsx
  setuper/data/small_sample.gpkg
  setuper/data_collection.py
  setuper/dict2xml.py
  setuper/entities.py
  setuper/fake.py
  setuper/generated/empty_file.txt
  setuper/init.sql
  setuper/init_sample_project.sh
  setuper/micro_planning.py
  setuper/pyramid.py
  setuper/registry.py
  setuper/requirements.txt
  setuper/setuper.py
  setuper/submissions.py
Labels: release

#1028 IA-2346: multiselect, order selected options alphabetically
  hat/assets/js/apps/Iaso/domains/dataSources/utils.js
  package-lock.json
Labels: release

#1041 Update the AMI creation doc
  docs/AWS-Deployment.md
  scripts/create_ami.sh
Labels: release

#1044 POLIO-1412: Hotfix the error when the compaign is not linked to a country
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/tests/test_base.py
Labels: release

#1030 WC2-313: Form id is breaking form table
  hat/assets/js/apps/Iaso/components/Cells/BreakWordCell.tsx
  hat/assets/js/apps/Iaso/domains/forms/config/index.js
  hat/assets/js/apps/Iaso/domains/forms/config/index.spec.js
Labels: release

#1032 WC2-301 initial proposal to fix the two bugs in WC2-301
  iaso/api/workflows/import_export.py
  iaso/tests/api/workflows/test_import_export.py
Labels: release

#1066 IA-2657 update documentation with my local notes
  docs/pages/dev/reference/entities_in_iaso/entities_in_iaso.md
  docs/pages/dev/reference/sql_dashboard/SQL_Dashboard_feature.md
Labels: documentation

#1058 IA-2638: DOC add comments to mkDocs.yml
  mkdocs.yml
Labels: documentation

#1073 Test
  docs/index.md
Labels: documentation

#1050 IA-2565: Org units search change source should reset parent org unit
  hat/assets/js/apps/Iaso/components/filters/DatesRange.d.ts
  hat/assets/js/apps/Iaso/components/forms/InputComponent.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitFiltersContainer.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsFilters.tsx
  hat/assets/js/apps/Iaso/domains/projects/hooks/requests/useGetProjectsDropDown.ts
Labels: release

#1068 IA-2622 / IA-2623: Org units change requests instances details and files
  .eslintrc.json
  .gitignore
  hat/assets/js/apps/Iaso/components/Accordion/Accordion.tsx
  hat/assets/js/apps/Iaso/components/Accordion/AccordionDetails.tsx
  hat/assets/js/apps/Iaso/components/Accordion/AccordionSummary.tsx
  hat/assets/js/apps/Iaso/components/dialogs/ImageGalleryComponent.tsx
  hat/assets/js/apps/Iaso/components/files/DocumentsItemComponent.js
  hat/assets/js/apps/Iaso/components/files/DocumentsItemComponent.tsx
  hat/assets/js/apps/Iaso/components/files/DocumentsListComponent.js
  hat/assets/js/apps/Iaso/components/files/DocumentsListComponent.tsx
  hat/assets/js/apps/Iaso/components/files/LazyImagesListComponent.js
  hat/assets/js/apps/Iaso/components/files/LazyImagesListComponent.tsx
  hat/assets/js/apps/Iaso/components/files/VideoItemComponent.js
  hat/assets/js/apps/Iaso/components/files/VideoItemComponent.tsx
  hat/assets/js/apps/Iaso/components/files/VideosListComponent.js
  hat/assets/js/apps/Iaso/components/files/VideosListComponent.tsx
  hat/assets/js/apps/Iaso/components/maps/MarkerMapComponent.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/compare/components/InstanceDetail.tsx
  hat/assets/js/apps/Iaso/domains/instances/compare/components/InstanceDetailRaw.tsx
  hat/assets/js/apps/Iaso/domains/instances/compare/messages.ts
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsInfos.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsLocation.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentRich.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFilesListComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFilesListComponent.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/PaginatedInstancesFiles.js
  hat/assets/js/apps/Iaso/domains/instances/details.tsx
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/instances/types/instance.ts
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesInfos.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableHead.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableRow.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useGetApprovalProposal.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/utils/filesUtils.ts
Labels: release

#1081 POLIO-1353 Fixes on Supply Chain and Stock Management
  hat/assets/js/apps/Iaso/components/nav/TabWithInfoIcon.tsx
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/useVaccineStockManagementTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/mocks/mockVaccineStockList.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/PreAlerts/PreAlert.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReport.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReports.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/VaccineSupplyChain.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
  plugins/polio/migrations/0163_auto_20240123_1435.py
  plugins/polio/models.py
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#1082 POLIO-1444: change translation
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
Labels: release

#1084 Polio Line List Import Fix (Sentry #4918303183)
  plugins/polio/models.py
  plugins/polio/tests/fixtures/linelist_notification_test.xlsx
  plugins/polio/tests/fixtures/~$linelist_notification_test.xlsx
Labels: release

#1064 Polio-1403: remove useless hook
  hat/assets/js/apps/Iaso/hooks/taskMonitor.ts
  plugins/polio/js/src/domains/LQAS-IM/shared/RefreshLqasData.tsx
Labels: release

#1072 IA-2613: Use Org unit change requests old values while approved
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesButtons.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesDeleteButtons.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesDialogTitle.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesInfos.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableRow.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/types.ts
  iaso/models/org_unit.py
  iaso/tests/api/org_unit_change_requests/test_serializers.py
  iaso/tests/models/test_org_unit_change_request.py
Labels: release

#1080 Add Doc section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
