Repository BLSQ/iaso, pull requests merged in 2024-12, with the labels that each got.

#1803 IA-3486: Reorganize Menu entries
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/constants/messages.js
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/groupSets/index.tsx
  hat/assets/js/cypress/integration/05 - orgUnits/changesConfiguration/changeRequestConfiguration.spec.js
  hat/assets/js/cypress/integration/05 - orgUnits/reviewChanges/changeRequest.spec.js
  hat/assets/js/cypress/integration/08 - orgUnitTypes/list.spec.js
  hat/assets/js/cypress/integration/10 - groups/list.spec.js
  hat/assets/js/cypress/integration/12 - datasources/list.spec.js
  hat/assets/js/cypress/integration/16 - links/list.spec.js
  hat/assets/js/cypress/integration/17 - completeness/list.spec.js
Labels: release, postrelease

#1812 IA-3540 restrict payments list by user location
  hat/assets/js/apps/Iaso/domains/orgUnits/index.tsx
  hat/assets/js/apps/Iaso/domains/payments/components/PaymentLotActionCell.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentColumns.tsx
  hat/assets/js/apps/Iaso/domains/payments/types.ts
  iaso/api/payments/serializers.py
  iaso/api/payments/views.py
  iaso/models/base.py
  iaso/tests/api/payments/test_payment_lots.py
  iaso/tests/api/payments/test_potential_payments.py
Labels: release

#1829 POLIO-1715: supply chain reorder lines
  plugins/polio/api/vaccines/supply_chain.py
Labels: release

#1676 WC2-566 Add v1 of health pyramid setup script from a CSV
  scripts/create_health_pyramid_from_csv.py
Labels: release

#1832 IA-3026: In the org unit search, the loading of the map tab should only start when we switch to the map tab
  hat/assets/js/apps/Iaso/components/maps/tools/zoom-bar.js
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitFiltersContainer.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsFilters.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsMap.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TableList.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgUnit.ts
  package-lock.json
Labels: release

#1822 IA-3711: add methods to test mixins
  iaso/test.py
  plugins/polio/tests/api/test.py
Labels: release

#1828 Polio-1708 delete deprecated endpoints
  plugins/polio/api/dashboards/forma.py
  plugins/polio/api/lqas_im/im_stats.py
  plugins/polio/api/urls.py
  plugins/polio/tests/test_base.py
Labels: release

#1830 POLIO-1753: split pdf repository data per vaccine per round
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/api/vaccines/repository.py
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Campaigns/MainDialog/CreateEditDialog.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/WarningModal.tsx
  plugins/polio/js/src/domains/VaccineModule/Repository/hooks/useVaccineRepositoryColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/Repository/messages.ts
  plugins/polio/migrations/0206_delete_unused_scopes.py
  plugins/polio/models/base.py
  plugins/polio/tests/api/test.py
  plugins/polio/tests/test_api.py
  plugins/polio/tests/test_vaccine_repository.py
Labels: postrelease

#1816 [IA-3702] Cleaned prints in migration files
  iaso/migrations/0104_seed_form_possible_fields_20210825_0949.py
  iaso/migrations/0178_remove_beneficiary_user_perm.py
  plugins/polio/migrations/0041_move_preparedness_polio.py
  plugins/polio/migrations/0202_populate_forma_round.py
  plugins/polio/migrations/0203_auto_20241119_1153.py
Labels: postrelease

#1867 IA-3781: Orgunit detail double call to api/groups
  hat/assets/js/apps/Iaso/domains/orgUnits/details.js
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks.js
Labels: release

#1857 WC2-523 Add storage logs to bulk update
  iaso/api/storage.py
  iaso/tasks/process_mobile_bulk_upload.py
  iaso/tests/fixtures/mobile_bulk_uploads/storage_logs_and_change_requests/5475bfcf-5a3f-4170-9d88-245d89352362/3_2_809f9a76-3f3f-4033-aefb-98f47fb2ccaf_2024-12-03_12-46-06.xml
  iaso/tests/fixtures/mobile_bulk_uploads/storage_logs_and_change_requests/instances.json
  iaso/tests/fixtures/mobile_bulk_uploads/storage_logs_and_change_requests/storageLogs.json
  iaso/tests/tasks/test_process_mobile_bulk_upload.py
Labels: release

#1870 POLIO-1785, POLIO-1786: change vaccine repo table defaults
  plugins/polio/api/vaccines/repository_forms.py
  plugins/polio/js/src/domains/VaccineModule/Repository/forms/hooks/useGetVaccineReporting.ts
  plugins/polio/tests/test_vaccine_repository_forms.py
Labels: release

#1873 IA-3790: Only 1 editable OUT on OU creation page while 2 were configured
  iaso/api/profiles/profiles.py
Labels: release

#1860 IA-3628: Change requests: filter use default datasource by default, add advanced filters
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Filter/ReviewOrgUnitChangesFilter.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useGetApprovalProposals.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/types.ts
  hat/assets/js/cypress/integration/05 - orgUnits/reviewChanges/changeRequest.spec.js
  iaso/api/groups.py
  iaso/api/org_unit_change_requests/filters.py
  iaso/api/org_unit_change_requests/views.py
Labels: release

#1877 [IA-3797] Fixed error login without profile
  iaso/api/profiles/profiles.py
  iaso/tests/api/test_profiles.py
Labels: bug

#1862 POLIO-1788, POLIO-1752, POLIO-1716, POLIO-1732: Vaccine module improvements
  plugins/polio/api/vaccines/repository_reports.py
  plugins/polio/js/src/domains/VaccineModule/Repository/VaccineRepository.tsx
  plugins/polio/migrations/0208_alter_vaccinerequestform_rounds_and_more.py
  plugins/polio/migrations/0209_merge_20241216_1100.py
  plugins/polio/models/base.py
  plugins/polio/tasks/archive_vaccine_stock_for_rounds.py
Labels: release
