Repository BLSQ/iaso, pull requests merged in 2024-04, with the labels that each got.

#1233 WC2-361: Calculations for average weight gain
  plugins/wfp/admin.py
  plugins/wfp/common.py
  plugins/wfp/management/commands/wfp_etl_Under5.py
  plugins/wfp/migrations/0011_journey_weight_difference_journey_weight_loss.py
  plugins/wfp/migrations/0012_rename_weight_difference_journey_initial_weight_and_more.py
  plugins/wfp/models.py
  plugins/wfp/templates/debug.html
Labels: release

#1230 IA-2813 allow event date to come from the period
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/mappings/actions.js
  hat/assets/js/apps/Iaso/domains/mappings/components/GeneraMappingInfo.js
  hat/assets/js/apps/Iaso/domains/mappings/details.js
  hat/assets/js/apps/Iaso/domains/mappings/messages.js
  iaso/api/mapping_versions.py
  iaso/dhis2/datavalue_exporter.py
  iaso/models/base.py
  iaso/periods.py
  iaso/tests/test_periods.py
  iaso/tests/tests_events_exporter.py
  scripts/sort_translations.py
  scripts/update_trads.py
Labels: release

#1216 POLIO-1498 Rename outgoing movement into form a unusable vials
  plugins/polio/api/vaccines/stock_management.py
Labels: release

#1217 POLIO-1499 Remane destruction report items in Stock management
  plugins/polio/api/vaccines/stock_management.py
Labels: release

#1239 IA-2837 update change request front
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/libs/utils.tsx
Labels: release

#1225 IA-2710 Allow to erase a field in a Change Request
  docs/pages/dev/reference/API/org_unit_registry.md
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/libs/utils.tsx
  iaso/admin.py
  iaso/api/org_unit_change_requests/serializers.py
  iaso/migrations/0275_orgunitchangerequest_stored_requested_fields.py
  iaso/migrations/0276_data_populate_requested_fields.py
  iaso/migrations/0277_rename_stored_requested_fields_orgunitchangerequest_requested_fields.py
  iaso/models/org_unit.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/api/org_unit_change_requests/test_serializers.py
  iaso/tests/models/test_org_unit_change_request.py
Labels: release

#1240 IA-2817 no dash in app
  hat/assets/js/apps/Iaso/constants/filters.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectFeatureFlags.tsx
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectsDialog.tsx
  hat/assets/js/apps/Iaso/domains/projects/messages.ts
Labels: release

#1238 POLIO-1497: SIA Calendar: dotted lines for Test/on hold campaigns
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/js/config.tsx
  plugins/polio/js/src/domains/Calendar/Calendar.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/CampaignsFilters.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/IsTestLegend.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/TogglePeriod.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/RoundCell.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/index.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/types.ts
  plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
  plugins/polio/js/src/domains/Campaigns/CampaignsList/Dashboard.tsx
  plugins/polio/js/src/domains/Campaigns/hooks/api/useGetCampaigns.ts
Labels: postrelease

#1244 IA-2862: HOTFIX fix date reset UI
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/libs/utils.tsx
Labels: hotfix

#1257 DOC - Better hierarchy of titles in IASO doc
  docs/pages/users/reference/user_guide/user_guide.md
  mkdocs.yml
Labels: documentation

#1253 IA-2884 improve dhis2 error message parsing when conflicts don't have…
  iaso/dhis2/datavalue_exporter.py
  iaso/tests/fixtures/dhis2/event-create-error-235-type.json
  iaso/tests/tests_events_exporter.py
Labels: release

#1249 POLIO-1465: Supply chain prefill VAR
  hat/assets/js/apps/Iaso/components/forms/InputComponent.tsx
  package-lock.json
  plugins/polio/js/src/components/Inputs/Select.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/PreAlerts/PreAlert.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReport.tsx
Labels: release

#1258 POLIO-1541 add stocks fields to api for dashboarding
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/tests/test_supply_chain_dashboards.py
Labels: release

#1267 IA-2741: Create option in Forms advanced setting to enable validation
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
  hat/assets/js/apps/Iaso/domains/forms/constants.ts
  hat/assets/js/apps/Iaso/domains/forms/detail.spec.js
  hat/assets/js/apps/Iaso/domains/forms/detail.tsx
  hat/assets/js/apps/Iaso/domains/forms/messages.js
  hat/assets/js/apps/Iaso/domains/forms/requests.js
  hat/assets/js/apps/Iaso/domains/forms/types/forms.ts
  iaso/api/forms.py
  iaso/tests/api/test_forms_serializers.py
Labels: release

#1261 IA-2786: Add data download (CSV/Excel) blurred buttons on the submissions page
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
  hat/assets/js/apps/Iaso/domains/instances/index.js
  hat/assets/js/apps/Iaso/domains/instances/messages.js
Labels: release

#1272 IA-2830: add write permission to compareInstances route config
  hat/assets/js/apps/Iaso/constants/routes.js
Labels: release
