Repository BLSQ/iaso, pull requests merged in 2024-02, with the labels that each got.

#1048 IA-2021:DOC move doc from wikijs
  docs/pages/users/how_to/create_new_documentation_page/create_new_documentation_page.md
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/duplicate_admin.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/menu.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/project.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/setupaccount_api.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/sourceversion.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/update_pyramid.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/attachments/update_source.png
  docs/pages/users/how_to/setup_an_empty_iaso_account/setup_an_empty_iaso_account.md
  docs/pages/users/how_to/setup_dhis2_login_in_iaso/attachments/external_auth.png
  docs/pages/users/how_to/setup_dhis2_login_in_iaso/attachments/feature_flag.png
  docs/pages/users/how_to/setup_dhis2_login_in_iaso/attachments/user.png
  docs/pages/users/how_to/setup_dhis2_login_in_iaso/setup_dhis2_login_in_iaso.md
Labels: documentation

#1125 Wc2 318 fix bug where deleted submissions and beneficiaries are not ignored by the etl
  plugins/wfp/common.py
  plugins/wfp/migrations/0010_alter_journey_beneficiary_alter_step_visit_and_more.py
  plugins/wfp/models.py
  plugins/wfp/tasks.py
  plugins/wfp/templates/delete_beneficiaries_analytics.html
  plugins/wfp/urls.py
  plugins/wfp/views.py
Labels: release

#1123 IA-2643: Org Unit change requests filters
  docs/pages/dev/reference/API/org_unit_registry.md
  hat/assets/js/apps/Iaso/constants/routes.js
  hat/assets/js/apps/Iaso/domains/instances/hooks/useGetProfilesDropdown.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Filter/ReviewOrgUnitChangesFilter.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/ReviewOrgUnitChanges.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useGetApprovalProposals.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/types.ts
  iaso/api/org_unit_change_requests/filters.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
Labels: release

#1122 POLIO-1458 add target population field to Vaccine Request Form
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/migrations/0166_vaccinerequestform_target_population.py
  plugins/polio/models.py
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: release

#1127 POLIO-1460: add target population to supply chain front end
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/utils.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/validation.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
Labels: release

#1130 POLIO-1475: fix supplychain save button enabled/disabled state
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineSupplyChainDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/utils.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
Labels: release

#1132 POLIO-1477 add delete button in stocks
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/useVaccineStockManagementTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#1133 POLIO-1480: fix campaign options in formA
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditFormA.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
Labels: release

#1155 POLIO-1490 Adapt the list of in out events according to usable unusable vials
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#1135 IA-2697: Change request UI for org unit creation
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesButtons.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Dialogs/ReviewOrgUnitChangesDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/ReviewOrgUnitChanges.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableBody.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableHead.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/details/ReviewOrgUnitChangesDetailsTableRow.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/types.ts
  iaso/api/org_unit_change_requests/serializers.py
  iaso/tests/api/org_unit_change_requests/test_serializers.py
Labels: release

#1153 IA-2709: Multilingual forms on WEB
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
Labels: release

#1151 IA-2567: Adding Tooltip next to the search field for org unit
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsFilters.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/messages.js
Labels: release

#1147 IA-2234: use AlertModal from bluesquare-components
  hat/assets/js/apps/Iaso/components/AlertModal/AlertModal.tsx
  hat/assets/js/apps/Iaso/domains/tasks/components/NotificationImportDetailModal.tsx
  package-lock.json
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundDatesHistory/RoundDatesHistoryModal/RoundDatesHistoryModal.tsx
Labels: release

#1159 POLIO-1495 make fields optional
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/validation.ts
  plugins/polio/migrations/0167_auto_20240226_1352.py
  plugins/polio/models.py
Labels: release

#1152 POLIO-1488 hide lot numbers info in vaccine stock management
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditDestruction.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditFormA.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/validation.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
Labels: release

#1157 IA-2727 Feat: New field change_request_mode on Form
  iaso/api/instances.py
  iaso/migrations/0263_form_change_request_mode.py
  iaso/models/forms.py
  iaso/tests/api/org_unit_change_requests/test_change_request_on_new_reference_form.py
Labels: release

#1156 IA-2708 - Allow to retrieve OrgUnits via their IDs
  iaso/api/mobile/org_units.py
  iaso/api/query_params.py
  iaso/tests/api/test_mobile_orgunits.py
Labels: enhancement, release
