Repository BLSQ/iaso, pull requests merged in 2024-10, with the labels that each got.

#1680 IA-3478-IA-3479-IA-3480: Rename foms "Child/Enfant - Follow-up/Suivi" , "Child/Enfant - Registration/Enregistrement" and "Vaccination" project
  setuper/README.md
  setuper/additional_projects.py
  setuper/entities.py
Labels: release

#1681 WC2-515: Try to fix "'WSGIRequest' object has no attribute 'query_params'"
  plugins/wfp_auth/views.py
Labels: bug, release

#1664 IA-3123: Review the look and feel of permissions list (with Read/Write)
  docs/pages/dev/how_to/add_new_permission/add_new_permission.md
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsAttribution.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/config.tsx
  hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useSaveUserRole.ts
  hat/assets/js/apps/Iaso/domains/userRoles/validation.ts
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  hat/assets/js/apps/Iaso/domains/users/components/PermissionCheckBoxes.tsx
  hat/assets/js/apps/Iaso/domains/users/components/PermissionCheckbox.tsx
  hat/assets/js/apps/Iaso/domains/users/components/PermissionSwitch.tsx
  hat/assets/js/apps/Iaso/domains/users/components/PermissionsAttribution.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UserRolePermissions.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
  hat/assets/js/apps/Iaso/domains/users/config.js
  hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/menupermissions/constants.py
  iaso/api/permissions.py
  iaso/api/user_roles.py
  iaso/tests/api/test_permissions.py
  iaso/tests/api/test_user_roles.py
Labels: release

#1677 POLIO-1686: bOPV hide column
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Summary/VaccineStockManagementSummary.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/VaccineStockManagementDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/VaccineStockManagementTable.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/useVaccineStockManagementTableColumns.tsx
Labels: release

#1674 IA-3457: Create a User Role in the setuper
  setuper/setuper.py
  setuper/user_roles_permissions.py
Labels: release

#1678 POLIO-1687 Adding caching after failing hotfix
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/tests/test_supply_chain_dashboards.py
Labels: release

#1673 IA-3472 fix duplicates in search with multiple projects
  iaso/api/group_sets/filters.py
Labels: release

#1686 POLIO-1674: fix vaccine auth cronjob
  cron.yaml
Labels: release

#1701 IA-3531, IA-3532, IA-3521: low-energy stuff
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/assignments/components/AssignmentsMap.tsx
Labels: release

#1695 WC2-515: Fix appId is ignored and always return first user
  plugins/wfp_auth/views.py
Labels: bug

#1724 [IA-3567] Update setuper doc
  setuper/README.md
Labels: documentation, release

#1725 [IA-3572] Setuper error after worker timeout
  setuper/iaso_api_client.py
Labels: enhancement, release

#1730 [IA-3569] Added DHIS2 module to setuper account
  setuper/setuper.py
Labels: enhancement, release

#1731 [IA-3570] Add HF form to setuper .georegistry project
  setuper/additional_projects.py
Labels: bug, release

#1727 [IA-3571] Added account_name parameter to setuper command
  setuper/README.md
  setuper/setuper.py
Labels: enhancement

#1685 POLIO-1685 missing var in supplychain list
  package-lock.json
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/components/Inputs/Select.tsx
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReport.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/validation.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
  plugins/polio/migrations/0198_remove_po_prefix.py
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: release

#1717 IA-3493: Clean up feature flags
  iaso/migrations/0304_auto_20241015_1017.py
Labels: enhancement, release

#1749 IA-3449: Spelling corrections
  hat/locale/fr/LC_MESSAGES/django.po
Labels: release

#1748 IA-3289: remove "null" label on Org unit bulk edit modal
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsMultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/index.tsx
Labels: release

#1750 POLIO-1683 Enable sorting of columns in Vaccine Stocks details
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#1739 IA-3466 Implement permissions for users with org unit types restrictions
  iaso/api/profiles/bulk_create_users.py
  iaso/api/profiles/profiles.py
  iaso/models/base.py
  iaso/tasks/profiles_bulk_update.py
  iaso/tests/api/test_org_units_bulk_update.py
  iaso/tests/api/test_orgunits.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/tests/models/test_profile.py
  iaso/tests/test_create_users_from_csv.py
Labels: release

#1755 [IA-3413] Update OrgUnit status after Change Request rejection
  iaso/models/org_unit.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/models/test_org_unit_change_request.py
Labels: bug

#1735 WC2-523: [WEB] NFC card field shows 0 for all beneficiaries even when card is assigned
  hat/assets/js/apps/Iaso/domains/entities/hooks/useGetBeneficiaryFields.ts
  hat/assets/js/apps/Iaso/domains/entities/types/beneficiary.ts
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContent.tsx
  hat/assets/js/apps/Iaso/domains/instances/details.tsx
  hat/assets/js/apps/Iaso/domains/storages/components/LinkToEntity.tsx
  hat/assets/js/apps/Iaso/domains/storages/details.tsx
  iaso/api/entity.py
  iaso/api/storage.py
  iaso/models/base.py
  iaso/models/entity.py
  iaso/tests/api/test_storage.py
Labels: release

#1751 IA-3592: Entity Duplicates: add "Parameters" field to analysis modals
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/entities/constants.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/hooks/api/analyzes.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/AnalyseAction.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/AnalysisModal.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/list/AnalysisModalParameters.tsx
  hat/assets/js/apps/Iaso/domains/entities/duplicates/messages.ts
  hat/assets/js/apps/Iaso/domains/entities/duplicates/types.ts
  iaso/api/deduplication/entity_duplicate_analyzis.py
  iaso/tests/api/deduplication/test_entities_deduplication.py
Labels: release
