Repository BLSQ/iaso, pull requests merged in 2024-06, with the labels that each got.

#1343 IA-3044: update link to user guide
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/LinkToInstance.tsx
Labels: release

#1342 IA-2992: View only permission for Planning
  hat/assets/js/apps/Iaso/constants/routes.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/completenessStats/CompletenessStatsFilters.tsx
  hat/assets/js/apps/Iaso/domains/plannings/components/LinkToPlanning.tsx
  hat/assets/js/apps/Iaso/domains/plannings/config.tsx
  hat/assets/js/apps/Iaso/domains/plannings/index.tsx
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/menupermissions/constants.py
  hat/menupermissions/migrations/0061_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/api/microplanning.py
  iaso/migrations/0281_replace_registry_permission_by_read_and_write_to_users_permission.py
  iaso/migrations/0282_replace_planning_permission_by_read_and_write_to_users_permission.py
  iaso/migrations/0283_merge_20240603_0930.py
  iaso/tests/test_microplanning.py
Labels: release

#1344 IA-3052: add scroll to instances visible columns
  hat/assets/js/apps/Iaso/components/tables/ColumnSelectDrawer/index.tsx
  hat/assets/js/apps/Iaso/domains/instances/index.js
Labels: release

#1326 IA-3022: update url in seed_data_test
  README.md
  iaso/management/commands/seed_test_data.py
Labels: release

#1352 IA-3065: fix mappings details crash
  hat/assets/js/apps/Iaso/domains/mappings/details.js
  hat/assets/js/apps/Iaso/domains/mappings/index.js
  hat/assets/js/apps/Iaso/routing/legacy.tsx
Labels: release

#1355 IA-3045: Registry: Pre-select a form in the lower part of the screen as well
  hat/assets/js/apps/Iaso/components/DisplayIfUserHasPerm.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
Labels: release

#1372 IA-3070: registry list select
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenList.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitPaper.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
Labels: release

#1380 POLIO-1563: pass country_id as number
  hat/assets/js/apps/Iaso/hooks/taskMonitor.ts
  plugins/polio/js/src/domains/LQAS-IM/shared/RefreshLqasData.tsx
Labels: release

#1381 IA-3075: show all instance locations on org unit map
  hat/assets/js/apps/Iaso/domains/forms/components/FormsFilterComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceDetailsLocation.tsx
Labels: release

#1370 IA-3071 Registry clean state, params on org unit change
  .eslintrc.json
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitChildrenList.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/OrgUnitPaper.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
  hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnit.ts
  hat/assets/js/apps/Iaso/domains/registry/index.tsx
Labels: release

#1388 IA-3094: Change text of the no permission screen
  hat/assets/js/apps/Iaso/components/errors/messages.js
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
Labels: release

#1392 POLIO-1568 HOTFIX: remove success snackbar from spreadsheet API query
  plugins/polio/js/src/domains/Campaigns/Preparedness/PreparednessConfig.js
  plugins/polio/js/src/domains/Campaigns/Preparedness/hooks/useGetPreparednessData.js
Labels: release

#1365 POLIO-1562 sub activities bugs
  hat/assets/js/apps/Iaso/domains/forms/detail.tsx
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/domains/Calendar/ExportCsvModal.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/map/VaccinesLegend.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/CreateEditDialog.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/PolioDialogTab.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/components/Modal/CreateEditSubActivity.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/components/SubActivityScopeField.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/api/useGetSubActivities.ts
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/api/useSaveSubActivity.ts
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/useSubActivityValidation.tsx
  plugins/polio/js/src/domains/Campaigns/hooks/api/useSaveCampaign.js
  plugins/polio/js/src/domains/Campaigns/hooks/api/useSaveCampaign.ts
Labels: release

#1265 IA-2841 mapping select multiple to boolean
  docker-compose.yml
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/mappings/actions.js
  hat/assets/js/apps/Iaso/domains/mappings/components/CreateMappingVersionDialogComponent.js
  hat/assets/js/apps/Iaso/domains/mappings/components/GeneraMappingInfo.js
  hat/assets/js/apps/Iaso/domains/mappings/components/HesabuHint.js
  hat/assets/js/apps/Iaso/domains/mappings/components/ObjectDumper.js
  hat/assets/js/apps/Iaso/domains/mappings/components/QuestionMappingForm.js
  hat/assets/js/apps/Iaso/domains/mappings/components/RecursiveTreeView.js
  hat/assets/js/apps/Iaso/domains/mappings/descriptor.js
  hat/assets/js/apps/Iaso/domains/mappings/details.js
  hat/assets/js/apps/Iaso/domains/mappings/hooks.js
  hat/assets/js/apps/Iaso/domains/mappings/index.js
  hat/assets/js/apps/Iaso/domains/mappings/messages.js
  hat/assets/js/apps/Iaso/domains/mappings/reducer.js
  hat/assets/js/apps/Iaso/redux/store.js
  hat/assets/js/test/utils/redux.js
  iaso/dhis2/datavalue_exporter.py
  iaso/dhis2/form_mapping.py
  iaso/management/commands/seed_test_data.py
  iaso/models/base.py
  iaso/models/forms.py
  iaso/odk/parsing.py
  iaso/tests/tests_events_exporter.py
  testdata/seed-data-command-cvs_survey-mapping.json
  testdata/seed-data-command-cvs_survey.xlsx
Labels: postrelease

#1412 IA-3138: Add `prevent_add_if_duplicate_found` boolean to EntityType
  iaso/api/mobile/entity_type.py
  iaso/migrations/0286_entitytype_prevent_add_if_duplicate_found.py
  iaso/models/entity.py
Labels: enhancement

#1430 IA-3148 polio user guide
  hat/assets/js/apps/Iaso/domains/app/components/SidebarMenuComponent.js
Labels: release

#1427 POLIO-1589 incident reports add two new entries
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/useIncidentOptions.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
  plugins/polio/migrations/0182_alter_incidentreport_stock_correction.py
  plugins/polio/models.py
Labels: release

#1434 IA-3155: prevent registry crash
  hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/map/OrgUnitChildrenMap.tsx
  hat/assets/js/apps/Iaso/domains/registry/index.tsx
Labels: release

#1433 IA-2891: Registry glitches + IA-3047 support image types + IA-3161
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentRich.js
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/OrgUnitTitle.tsx
  hat/assets/js/apps/Iaso/domains/registry/config.tsx
Labels: release

#1428 Ia 2470 improve org unit logs
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/details.js
  hat/assets/js/apps/Iaso/domains/orgUnits/history/LogCompareComponent.js
  hat/assets/js/apps/Iaso/domains/orgUnits/history/LogValue.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/history/messages.js
Labels: release
