Repository BLSQ/iaso, pull requests merged in 2025-09, with the labels that each got.

#2389 [IA-4244] Change path of uploaded files
  hat/api_import/migrations/0006_alter_apiimport_file.py
  hat/api_import/models.py
  hat/api_import/tests.py
  hat/settings.py
  iaso/diffing/exporter.py
  iaso/management/commands/delete_accounts.py
  iaso/management/commands/delete_project.py
  iaso/migrations/0002_auto_20191001_1142_squashed_0100_auto_20210702_0835.py
  iaso/migrations/0012_instance_export_id.py
  iaso/migrations/0034_form_version_upload_to.py
  iaso/migrations/0207_formattachment.py
  iaso/migrations/0342_reportversion_created_by_reportversion_updated_by_and_more.py
  iaso/models/__init__.py
  iaso/models/base.py
  iaso/models/bulk_create_user_csv_file.py
  iaso/models/entity.py
  iaso/models/forms.py
  iaso/models/import_gpkg.py
  iaso/models/instances.py
  iaso/models/reports.py
  iaso/test.py
  iaso/tests/api/form_versions/test_form_versions.py
  iaso/tests/api/test_forms_attachment.py
  iaso/tests/api/test_import_gpkg.py
  iaso/tests/api/test_mobile_bulkuploads.py
  iaso/tests/models/test_account.py
  iaso/tests/models/test_bulk_create_user_csv_file.py
  iaso/tests/models/test_form_attachments.py
  iaso/tests/models/test_form_versions.py
  iaso/tests/models/test_import_gpkg.py
  iaso/tests/models/test_instance.py
  iaso/tests/models/test_report.py
  iaso/tests/tasks/test_process_mobile_bulk_upload.py
  iaso/tests/test_create_users_from_csv.py
  iaso/utils/dhis2.py
  iaso/utils/models/upload_to.py
Labels: enhancement

#2421 [POLIO-2001] Fix test flaky again
  plugins/polio/tests/test_vaccine_authorizations.py
Labels: bug

#2437 [IA-4484] Add CI files to plugin template
  plugins/template/.github/PULL_REQUEST_TEMPLATE.md
  plugins/template/.github/workflows/ci.yml
  plugins/template/.github/workflows/deploy.yml
Labels: enhancement

#2443 IA-4491: cannot scroll to send the new IASO account data for creation
  hat/assets/js/apps/Iaso/domains/setup/index.tsx
Labels: release
