Repository BLSQ/iaso, pull requests merged in 2025-01, with the labels that each got.

#1901 [IA-3285] Fix FR typos
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
Labels: bug

#1864 POLIO-1790: add lqas, im fields to SubActivity model
  plugins/polio/api/campaigns/subactivities.py
  plugins/polio/migrations/0209_subactivity_im_ended_at_subactivity_im_started_at_and_more.py
  plugins/polio/models/base.py
  plugins/polio/tests/test_subactivities.py
Labels: release

#1865 POLIO-1791: update front-end subactivities
  plugins/polio/api/campaigns/subactivities.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Campaigns/SubActivities/components/Modal/CreateEditSubActivity.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/useSubActivityValidation.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/messages.ts
  plugins/polio/js/src/domains/Campaigns/SubActivities/types.ts
  plugins/polio/migrations/0215_merge_20250107_1035.py
Labels: release

#1871 [IA-3782] Bulk push of GPS from submissions to OUs - backend
  hat/audit/models.py
  iaso/api/instances.py
  iaso/api/org_units.py
  iaso/api/tasks/create/instance_bulk_gps_push.py
  iaso/tasks/instance_bulk_gps_push.py
  iaso/tests/api/test_instances.py
  iaso/tests/tasks/test_instance_bulk_gps_push.py
  iaso/urls.py
  iaso/utils/models/common.py
Labels: enhancement, release

#1907 [IA-3667] Push bulk GPS from Instances to OrgUnits
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/dataSources/messages.js
  hat/assets/js/apps/Iaso/domains/instances/components/PushInstanceGps/PushBulkGpsWarning.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/PushInstanceGps/PushGpsDialogComponent.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/PushInstanceGps/PushGpsModalButton.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/PushInstanceGps/PushGpsWarningMessage.tsx
  hat/assets/js/apps/Iaso/domains/instances/hooks/useGetCheckBulkGpsPush.tsx
  hat/assets/js/apps/Iaso/domains/instances/hooks/useInstanceBulkgpspush.tsx
  hat/assets/js/apps/Iaso/domains/instances/messages.js
  hat/assets/js/apps/Iaso/domains/instances/types/instance.ts
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  hat/assets/js/apps/Iaso/libs/apiHooks.ts
  hat/audit/models.py
  iaso/api/instances.py
  iaso/api/org_units.py
  iaso/api/tasks/create/instance_bulk_gps_push.py
  iaso/tasks/instance_bulk_gps_push.py
  iaso/tests/api/test_instances.py
  iaso/tests/tasks/test_instance_bulk_gps_push.py
  iaso/urls.py
  iaso/utils/models/common.py
Labels: enhancement, release

#1906 POLIO-1774: delete rounds without campaign
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/migrations/0216_delete_rounds_without_campaign.py
  plugins/polio/models/base.py
  plugins/polio/tests/models/test_round_models.py
  plugins/polio/tests/test_api.py
Labels: release

#1889 IA-3433 Tasks view: Add extra filters on type, status and username (launcher)
  beanstalk_worker/__init__.py
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/tasks/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/tasks/config.tsx
  hat/assets/js/apps/Iaso/domains/tasks/hooks/api.ts
  hat/assets/js/apps/Iaso/domains/tasks/index.tsx
  hat/assets/js/apps/Iaso/domains/tasks/messages.js
  hat/assets/js/apps/Iaso/domains/tasks/types.ts
  iaso/api/common.py
  iaso/api/deduplication/filters.py
  iaso/api/forms.py
  iaso/api/instances.py
  iaso/api/payments/filters/utils.py
  iaso/api/payments/views.py
  iaso/api/source_versions.py
  iaso/api/tasks/create/copy_version.py
  iaso/api/tasks/create/dhis2_ou_importer.py
  iaso/api/tasks/create/export_mobile_setup.py
  iaso/api/tasks/create/import_gpkg.py
  iaso/api/tasks/create/instance_bulk_gps_push.py
  iaso/api/tasks/create/org_unit_bulk_location_set.py
  iaso/api/tasks/create/org_units_bulk_update.py
  iaso/api/tasks/create/payments_bulk_update.py
  iaso/api/tasks/create/profiles_bulk_update.py
  iaso/api/tasks/filters.py
  iaso/api/tasks/serializers.py
  iaso/api/tasks/views.py
  iaso/migrations/0314_task_created_by_task_iaso_task_account_72f14f_idx_and_more.py
  iaso/models/base.py
  iaso/tests/api/test_storage.py
  iaso/tests/api/test_tasks.py
  iaso/urls.py
  iaso/utils/__init__.py
  iaso/utils/date_and_time.py
  plugins/polio/tasks/api/create_refresh_preparedness_data.py
  plugins/polio/tasks/api/launch_vaccine_stock_archive.py
  plugins/polio/tasks/api/refresh_lqas_im_data.py
  plugins/polio/tests/api/test_budget.py
  plugins/polio/tests/api/test_budget_serializers.py
Labels: release

#1904 [POLIO-1795] Create new Budget API for dashboards
  plugins/polio/api/dashboards/budget.py
  plugins/polio/api/dashboards/campaign.py
  plugins/polio/api/urls.py
  plugins/polio/tests/api/dashboards/test_budget_process.py
  plugins/polio/tests/api/dashboards/test_campaign.py
Labels: enhancement, release

#1929 [IA-3878] Fix `created_at` is `null` when downloading OUCRC
  iaso/api/org_unit_change_request_configurations/views_mobile.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs_mobile.py
Labels: bug

#1927 Ia 3859 add tests for user filters
  iaso/tests/api/test_profiles_bulk_update.py
Labels: release

#1890 IA-3815 quarterlyNov backend
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/completeness/messages.js
  hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
  hat/assets/js/apps/Iaso/domains/forms/components/FormVersionsTable.tsx
  hat/assets/js/apps/Iaso/domains/forms/types/forms.ts
  hat/assets/js/apps/Iaso/domains/periods/components/PeriodPicker.tsx
  hat/assets/js/apps/Iaso/domains/periods/constants.js
  hat/assets/js/apps/Iaso/domains/periods/messages.js
  hat/assets/js/apps/Iaso/domains/periods/models.spec.js
  hat/assets/js/apps/Iaso/domains/periods/models.ts
  hat/assets/js/apps/Iaso/domains/periods/utils.js
  iaso/api/form_versions.py
  iaso/api/instances.py
  iaso/migrations/0314_alter_form_period_type.py
  iaso/migrations/0315_alter_form_period_type.py
  iaso/migrations/0316_merge_20250121_1321.py
  iaso/models/forms.py
  iaso/periods.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/test_periods.py
Labels: release

#1919 POLIO-1823: Polio vaccine supply chain & stock management permissions: Rename Read and Write to respectively Non-admin Admin
  hat/menupermissions/constants.py
Labels: release

#1914 POLIO-1821 show sub activity in calendar
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/domains/Calendar/Calendar.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/HasSubActivityLegend.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/RoundCell.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/types.ts
  plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
Labels: release

#1926 POLIO-1820: update calendar api
  iaso/test.py
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/api/rounds/round.py
  plugins/polio/api/vaccines/repository_forms.py
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/domains/Calendar/Calendar.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/HasSubActivityLegend.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/RoundCell.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/types.ts
  plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
  plugins/polio/models/base.py
  plugins/polio/preparedness/spreadsheet_manager.py
  plugins/polio/tasks/weekly_email.py
  plugins/polio/tests/api/test.py
  plugins/polio/tests/models/test_campaign_models.py
  plugins/polio/tests/test_api.py
  plugins/polio/tests/test_base.py
  plugins/polio/tests/test_campaign_calendar.py
  plugins/polio/tests/test_vaccine_repository_forms.py
Labels: release

#1921 POLIO-1723: Have "Test/On hold" campaigns option at Round level
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/js/src/components/Inputs/BooleanInput.js
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Budget/types.ts
  plugins/polio/js/src/domains/Campaigns/MainDialog/usePolioDialogTabs.tsx
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundForm.tsx
  plugins/polio/js/src/domains/Campaigns/Rounds/RoundsForm.tsx
  plugins/polio/js/src/hooks/useFormValidator.js
  plugins/polio/js/src/styles/theme.js
  plugins/polio/migrations/0217_round_is_test.py
  plugins/polio/models/base.py
Labels: release

#1928 WC2-594 + IA-3745 + IA-3841 Improvements and fixes for multi-account users
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
  hat/assets/js/apps/Iaso/domains/users/messages.ts
  hat/assets/js/apps/Iaso/domains/users/types.ts
  iaso/api/accounts.py
  iaso/api/profiles/profiles.py
  iaso/tests/api/test_account.py
  iaso/utils/__init__.py
Labels: release

#1936 IA-3883 try to debug flacky test on github ci
  iaso/tests/api/test_instances.py
Labels: release

#1948 POLIO-1873: fix nopv-bopv dropdown in polio
  plugins/polio/api/campaigns/campaigns.py
Labels: hotfix
