Repository BLSQ/iaso, pull requests merged in 2025-06, with the labels that each got.

#2190 POLIO-1924: Earmarked vials pre fill
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditEarmarked.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/vrf.tsx
Labels: release

#2184 IA-4249 limit pagination lower when shapes are requested
  iaso/api/mobile/org_units.py
  iaso/tests/api/test_mobile_orgunits.py
Labels: release

#2196 POLIO-1949_supply_chain_filters
  .gitignore
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/tests/api/vaccine_supply_chain/test_vaccine_supply_chain.py
Labels: release

#2032 IA-3802 enketo erases special values from mobile
  iaso/api/enketo.py
  iaso/enketo/__init__.py
  iaso/enketo/enketo_url.py
  iaso/enketo/enketo_xml.py
  iaso/management/commands/seed_test_data.py
  iaso/tests/api/test_enketo.py
  iaso/tests/fixtures/form_rapide_1666691000_with_injectables.xlsx
  iaso/tests/fixtures/form_rapide_1666691000_with_injectables.xml
Labels: postrelease

#2203 WC2-697: Configure ETL - Ethiopia
  plugins/wfp/common.py
  plugins/wfp/management/commands/ethiopia/Under5.py
  plugins/wfp/management/commands/etl_eth.py
  plugins/wfp/tasks.py
  plugins/wfp/templates/debug.html
  plugins/wfp/views.py
Labels: release

#2222 WC2-736: another duplicate issue
  iaso/api/deduplication/algos/levenshtein.py
  iaso/tests/api/deduplication/test_entities_deduplication.py
Labels: release

#2221 [IA-4268] Add MD5 checksum to FormVersions
  iaso/api/enketo.py
  iaso/api/form_attachments.py
  iaso/api/form_versions.py
  iaso/enketo/__init__.py
  iaso/enketo/md5_file.py
  iaso/migrations/0330_formversion_md5.py
  iaso/models/forms.py
  iaso/tests/utils/test_encryption.py
  iaso/utils/encryption.py
Labels: enhancement

#2232 [IA-4302] Fetch OrgUnit.code from DHIS2
  iaso/tasks/dhis2_ou_importer.py
  iaso/tests/fixtures/dhis2/orgunits.json
  iaso/tests/fixtures/dhis2/orgunits_strange_geom.json
  iaso/tests/tasks/test_dhis2_ou_importer.py
  iaso/tests/test_pyramid_exporter.py
Labels: enhancement

#2238 [IA-4303] Add OrgUnit.code to XLSX/CSV exports
  iaso/api/org_units.py
  iaso/test.py
  iaso/tests/api/payments/test_payment_lots.py
  iaso/tests/api/test_orgunits.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_storage.py
Labels: enhancement

#2249 [IA-4305] Search OrgUnits by code
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/messages.ts
  iaso/api/org_unit_search.py
  iaso/api/org_units.py
  iaso/tests/api/test_orgunits.py
Labels: enhancement, release

#2235 IA-4318 Improve migration
  iaso/migrations/0328_auto_20250619_1436.py
Labels: release

#2234 HOTFIX IA-4318 Comment data migration
  iaso/migrations/0328_auto_20250619_1436.py
Labels: release
