Repository BLSQ/iaso, pull requests merged in 2025-02, with the labels that each got.

#1959 POLIO-1842: Supply Chain: VAR saving error
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReport.tsx
Labels: release

#1938 POLIO-1758 Earmarked stock
  .github/workflows/main.yml
  iaso/api/storage.py
  iaso/test.py
  plugins/polio/admin.py
  plugins/polio/api/urls.py
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/constants/urls.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Summary/VaccineStockManagementSummary.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Table/VaccineStockManagementDetailsTable.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Table/useVaccineStockManagementDetailsColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/VaccineStockManagementDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditEarmarked.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/dropdownOptions.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/validation.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/VaccineStockVariation.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/constants.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/types.ts
  plugins/polio/migrations/0218_earmarkedstock.py
  plugins/polio/migrations/0221_merge_20250211_1527.py
  plugins/polio/models/base.py
  plugins/polio/tests/test_vaccine_stock_earmarked.py
Labels: postrelease

#1949 POLIO-1781 Create a "standard chronogram" for all upcoming rounds of a Polio campaign
  calendar_2022-10-01
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/api/rounds/round.py
  plugins/polio/migrations/0222_data_migration_auto_create_chronograms.py
  plugins/polio/models/base.py
  plugins/polio/models/chronogram.py
  plugins/polio/tests/api/campaigns/__init__.py
  plugins/polio/tests/api/campaigns/test_campaigns_1.py
  plugins/polio/tests/api/campaigns/test_campaigns_2.py
  plugins/polio/tests/api/campaigns/test_campaigns_calculator.py
  plugins/polio/tests/api/campaigns/test_campaigns_create_all_rounds_scopes_csv.py
  plugins/polio/tests/api/campaigns/test_campaigns_csv.py
  plugins/polio/tests/api/campaigns/test_campaigns_preparedness.py
  plugins/polio/tests/api/campaigns/test_campaigns_scopes_export_csv.py
  plugins/polio/tests/api/campaigns/test_campaigns_team.py
  plugins/polio/tests/api/chronogram/__init__.py
  plugins/polio/tests/api/chronogram/test_chronogram_filters.py
  plugins/polio/tests/api/chronogram/test_chronogram_serializers.py
  plugins/polio/tests/api/chronogram/test_chronogram_views.py
  plugins/polio/tests/api/dashboards/__init__.py
  plugins/polio/tests/api/dashboards/test_campaign.py
  plugins/polio/tests/api/dashboards/test_subactivities.py
  plugins/polio/tests/api/test.py
  plugins/polio/tests/api/test_lqasim_polio.py
  plugins/polio/tests/models/test_campaign_models.py
  plugins/polio/tests/models/test_chronogram.py
  plugins/polio/tests/models/test_round_models.py
  plugins/polio/tests/test_vaccine_repository_forms.py
  plugins/polio/tests/test_vaccine_stock_archive_task.py
  plugins/polio/tests/test_vaccine_stock_earmarked.py
  plugins/polio/tests/test_vaccine_stock_management.py
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: postrelease

#1917 [POLIO-1730] Scanning files for viruses - PoC
  README.md
  docker-compose.yml
  docker/docker-compose-clamav.yml
  docs/pages/dev/reference/clamav/clamav.en.md
  docs/pages/dev/reference/clamav/clamav.fr.md
  docs/pages/dev/reference/env_variables/env_variables.en.md
  hat/settings.py
  hat/urls.py
  iaso/api/form_attachments.py
  iaso/tests/api/test_forms_attachment.py
  iaso/tests/fixtures/clamav/eicar.txt
  iaso/tests/fixtures/clamav/safe.jpg
  iaso/tests/utils/test_clamav.py
  iaso/utils/clamav.py
  iaso/views.py
  requirements.txt
Labels: enhancement

#1964 [IA-2674] Only return Workflows for the requested project
  iaso/api/workflows/mobile.py
  iaso/models/workflow.py
  iaso/tests/api/test_entity_types.py
  iaso/tests/api/workflows/base.py
  iaso/tests/api/workflows/test_workflows.py
  iaso/tests/api/workflows/test_workflows_mobile.py
Labels: enhancement

#1951 [POLIO-1802] Delete subactivity scopes on scope level switch
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Campaigns/MainDialog/PolioDialogTab.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/PolioDialogTabs.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/usePolioDialogTabs.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/useSubActivityValidation.tsx
  plugins/polio/js/src/domains/Campaigns/hooks/useSubActivityTabTooltip.tsx
  plugins/polio/services/__init__.py
  plugins/polio/services/campaign.py
  plugins/polio/tests/api/campaigns/test_campaigns_1.py
Labels: enhancement

#1920 IA-3870 Upgrade PostgreSQL from version 12 to version 16
  .github/workflows/main.yml
  README.md
  docker-compose.yml
  docker/db/Dockerfile
  docker/db/initdb-postgis.sh
  docker/db/update-postgis.sh
  docs/pages/dev/reference/sql_dashboard/SQL_Dashboard_feature.en.md
Labels: DO NOT MERGE

#1989 HOTFIX: POLIO-1853: Make launch powerbi endpoint public
  plugins/polio/api/dashboards/launch_powerbi.py
Labels: release

#1980 IA-3881: Change request - Although not changing groups, groups seems to have change
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Components/HighlightFieldsChanges.tsx
Labels: release

#1984 IA-3971: Improve paginated groups api
  iaso/api/groups.py
Labels: release

#1981 HOTFIX: POLIO-1722 update refreshpowerbi endpoint
  iaso/api/tasks/views.py
  iaso/utils/powerbi.py
  plugins/polio/api/dashboards/launch_powerbi.py
  plugins/polio/tasks/api/refresh_vrf_dashboard_data.py
  plugins/polio/tests/test_refresh_lqas_data.py
  plugins/polio/tests/test_refresh_powerbi.py
Labels: release

#1932 [IA-3882] Fix some endpoints return 200 with empty value when authentication is required but not satisfied
  iaso/api/forms.py
  iaso/api/mobile/org_units.py
  iaso/api/org_unit_types/viewsets.py
  iaso/permissions.py
  iaso/tests/api/test_form_versions.py
  iaso/tests/api/test_forms.py
  iaso/tests/api/test_mobile_orgunits.py
  iaso/tests/api/test_org_unit_types.py
Labels: bug

#1992 IA-3964: Disclaimer in top bar appears on top if multi account activated
  hat/assets/js/apps/Iaso/components/nav/TopBarComponent.js
Labels: release

#1991 IA-3967: Org unit search use default version
  hat/assets/js/apps/Iaso/domains/home/hooks/useGetOrgunitsExtraPath.ts
Labels: release

#1982 Polio-1822: Vaccine stock export
  plugins/polio/api/vaccines/common.py
  plugins/polio/api/vaccines/export_utils.py
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/VaccineStockManagementDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
Labels: release

#1987 IA-3968: Navigation of pages (Orgunit Search) is reset to 1 after going to page 2
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TableList.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetOrgUnits.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/index.tsx
  hat/assets/js/apps/Iaso/hooks/useQueryUpdateListener.ts
Labels: release

#1975 IA-3955: Ignore paging param on datasource api querry used to filter groups
  hat/assets/js/apps/Iaso/domains/dataSources/requests.js
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/config.js
  iaso/api/data_sources.py
  iaso/api/source_versions.py
  iaso/tests/api/test_data_sources.py
  iaso/tests/api/test_source_versions.py
Labels: release

#1978 POLIO-1743 Define and add editing permission for stock variation
  calendar_2022-10-01
  hat/assets/js/apps/Iaso/components/files/pdf/DocumentUploadWithPreview.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/menupermissions/constants.py
  hat/menupermissions/migrations/0069_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  package-lock.json
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/api/vaccines/permissions.py
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/constants/permissions.ts
  plugins/polio/js/src/constants/routes.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/VaccineStockVariation.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/VaccineStockManagement.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/PreAlerts/PreAlert.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReport.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Table/useVaccineSupplyChainTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/VaccineSupplyChain.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/utils.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
  plugins/polio/migrations/0223_destructionreport_created_at_and_more.py
  plugins/polio/models/base.py
  plugins/polio/tests/test_vaccine_stock_earmarked.py
  plugins/polio/tests/test_vaccine_stock_management.py
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: release, user tested

#1985 [WC2-673] Adding some documentation
  docs/pages/dev/how_to/attach_file_to_forms/attach_file_to_forms.en.md
  docs/pages/dev/how_to/attach_file_to_forms/attach_file_to_forms.fr.md
  docs/pages/dev/how_to/attach_file_to_forms/attachments/add_or_update.en.png
  docs/pages/dev/how_to/attach_file_to_forms/attachments/add_or_update.fr.png
  docs/pages/dev/how_to/attach_file_to_forms/attachments/form_attachments.en.png
  docs/pages/dev/how_to/attach_file_to_forms/attachments/form_attachments.fr.png
  docs/pages/dev/how_to/attach_file_to_forms/attachments/form_details.en.png
  docs/pages/dev/how_to/attach_file_to_forms/attachments/form_details.fr.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_actions.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_change_edition.en.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_change_edition.fr.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_follow_up_edition.en.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_follow_up_edition.fr.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_workflows.en.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/entity_type_workflows.fr.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/workflow_edition.en.png
  docs/pages/dev/how_to/create_entity_workflow/attachments/workflow_edition.fr.png
  docs/pages/dev/how_to/create_entity_workflow/create_entity_workflow.en.md
  docs/pages/dev/how_to/create_entity_workflow/create_entity_workflow.fr.md
  docs/pages/dev/how_to/create_forms_for_entities/create_forms_for_entities.en.md
  docs/pages/dev/how_to/create_forms_for_entities/create_forms_for_entities.fr.md
  docs/pages/dev/how_to/iaso_special_question_names/iaso_special_question_names.en.md
  docs/pages/dev/how_to/iaso_special_question_names/iaso_special_question_names.fr.md
  docs/pages/dev/how_to/iaso_specific_intents/iaso_specific_intents.en.md
  docs/pages/dev/how_to/iaso_specific_intents/iaso_specific_intents.fr.md
  docs/pages/users/reference/iaso_concepts/iaso_concepts.en.md
  docs/pages/users/reference/iaso_concepts/iaso_concepts.fr.md
  docs/pages/users/reference/iaso_modules/iaso_modules.en.md
Labels: documentation
