Repository BLSQ/iaso, pull requests merged in 2025-07, with the labels that each got.

#2251 [IA-4306] Add OrgUnit.code to geopackages
  iaso/gpkg/export_gpkg.py
  iaso/gpkg/import_gpkg.py
  iaso/tests/fixtures/gpkg/minimal.gpkg
  iaso/tests/gpkg/test_export.py
  iaso/tests/gpkg/test_export2.py
  iaso/tests/gpkg/test_import.py
Labels: enhancement, postrelease

#2253 [IA-4307] Add OrgUnit.code to differ actions
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/dataSources/components/sync/ConfirmSyncButton.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/components/sync/SyncDialog.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/hooks/useCreateJsonDiffAsync.ts
  hat/assets/js/apps/Iaso/domains/dataSources/messages.js
  hat/assets/js/apps/Iaso/domains/dataSources/utils.js
  iaso/api/source_versions_serializers.py
  iaso/diffing/comparisons.py
  iaso/diffing/differ.py
  iaso/diffing/exporter.py
  iaso/tests/api/data_source_versions_synchronization/test_serializers.py
  iaso/tests/api/data_source_versions_synchronization/test_views.py
  iaso/tests/api/source_version/test_serializers.py
  iaso/tests/api/source_version/test_source_versions.py
  iaso/tests/diffing/test_differ.py
  iaso/tests/diffing/test_dumper.py
  iaso/tests/diffing/utils.py
  iaso/tests/fixtures/pyramid_diff_csv/diff_csv_with_group_filtering.csv
  iaso/tests/fixtures/pyramid_diff_csv/diff_happy_path.csv
  iaso/tests/tasks/test_export_dhis2.py
Labels: enhancement

#2246 [WC2-778] Try to fix CIAM login for Ethiopia
  .github/workflows/main.yml
  Makefile
  hat/settings_test.py
  iaso/admin/base.py
  iaso/admin/user_admin.py
  iaso/api/profiles/profiles.py
  iaso/models/tenant_users.py
  iaso/test.py
  iaso/tests/models/test_tenant_users.py
  plugins/wfp_auth/tests/__init__.py
  plugins/wfp_auth/tests/test_auth.py
  plugins/wfp_auth/views.py
Labels: bug, enhancement

#2269 [IA-3801] Invalid change requests are returned to the mobile
  iaso/api/org_unit_change_requests/views_mobile.py
  iaso/tests/api/org_unit_change_requests/test_change_request_on_new_reference_form.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests_mobile.py
Labels: bug

#2262 Cypress: Add color property on project on save
  hat/assets/js/cypress/integration/05 - orgUnits/list.spec.js
  hat/assets/js/cypress/integration/09 - projects/list.spec.js
Labels: release

#2280 IA-3605: Display field of type 'file' on instance detail page
  hat/assets/js/apps/Iaso/components/files/DocumentsItemComponent.tsx
  hat/assets/js/apps/Iaso/components/files/DocumentsListComponent.tsx
  hat/assets/js/apps/Iaso/components/files/VideoItemComponent.tsx
  hat/assets/js/apps/Iaso/components/files/VideosListComponent.tsx
  hat/assets/js/apps/Iaso/components/files/pdf/PdfPreview.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentRich.tsx
  hat/assets/js/apps/Iaso/domains/instances/index.tsx
  hat/assets/js/apps/Iaso/utils/filesUtils.ts
Labels: release

#2277 IA-4291: Completeness stats CSV export
  iaso/api/completeness_stats.py
  iaso/tests/api/test_completeness_stats.py
Labels: release

#2295 [POLIO-1974] Fix polio permissions in OrgUnits
  iaso/api/org_units.py
Labels: bug, release

#2315 IA-4396: Hide DHIS2-related fields on the interface if the DHIS2 module is not activated
  hat/assets/js/apps/Iaso/constants/menu.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
  hat/assets/js/apps/Iaso/domains/dataSources/components/VersionsDialog.js
  hat/assets/js/apps/Iaso/domains/dataSources/hooks/useVersionsDialogTableColumns.tsx
  hat/assets/js/apps/Iaso/domains/dataSources/utils.js
  hat/assets/js/apps/Iaso/domains/forms/components/FormActions.tsx
  hat/assets/js/apps/Iaso/domains/forms/config/index.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
  hat/assets/js/apps/Iaso/domains/users/utils.js
Labels: release

#2319 SLEEP-1622: Entity csv/xlsx high memory usage
  hat/assets/js/apps/Iaso/domains/entities/details.tsx
  iaso/admin/base.py
  iaso/api/entity.py
  iaso/models/entity.py
  iaso/tests/api/entities/test_entities.py
  iaso/tests/models/test_entity.py
Labels: release

#2334 IA-4406: display placeholder text when search not active
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/forms/components/FormsTable.tsx
  hat/assets/js/apps/Iaso/domains/forms/index.tsx
  hat/assets/js/apps/Iaso/domains/forms/messages.ts
  hat/assets/js/apps/Iaso/domains/instances/index.tsx
  hat/assets/js/apps/Iaso/domains/instances/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/components/TableList.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/messages.ts
  hat/assets/js/apps/Iaso/domains/registry/index.tsx
  package-lock.json
Labels: release
