Repository BLSQ/iaso, pull requests merged in 2025-04, with the labels that each got.

#2049 [IA-4058] Improve OrgUnit refs search
  iaso/api/org_unit_search.py
  iaso/api/org_units.py
  iaso/gpkg/README.md
  iaso/gpkg/export_gpkg.py
  iaso/gpkg/import_gpkg.py
  iaso/tests/api/test_orgunits.py
  iaso/tests/fixtures/gpkg/multiple-internal-ref-formats.gpkg
  iaso/tests/gpkg/test_import.py
  iaso/tests/utils/test_common.py
  iaso/utils/models/common.py
Labels: enhancement

#2075 POLIO-1873: vrf changes
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
Labels: release

#2078 [IA-4109] Add ruff format check to CI
  .git-blame-ignore-revs
  .github/workflows/main.yml
  hat/menupermissions/constants.py
  iaso/api/org_unit_search.py
  iaso/api/pages.py
  iaso/gpkg/import_gpkg.py
  iaso/migrations/0317_alter_account_modules.py
  iaso/migrations/0318_add_data_validation_module_to_accounts.py
  iaso/models/workflow.py
  iaso/tests/api/test_orgunits.py
  iaso/tests/api/test_pages.py
  iaso/tests/api/workflows/test_workflows.py
  iaso/tests/gpkg/test_import.py
  plugins/polio/api/vaccines/public_vaccine_stock.py
  plugins/polio/tests/models/test_round_models.py
  setuper/create_submission_with_picture.py
  setuper/entities.py
  setuper/setuper.py
  setuper/submissions.py
Labels: enhancement

#2011 IA-4004: Add a `Type` to OUCRC
  hat/assets/js/apps/Iaso/constants/urls.ts
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialogCreateFirstStep.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Filter/OrgUnitChangeRequestConfigsFilter.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/OrgUnitChangeRequestConfigs.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Tables/OrgUnitChangeRequestConfigsTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/constants.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useGetOUCRCCheckAvailabilityDropdownOptions.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useGetOrgUnitChangeRequestConfigs.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useRetrieveOrgUnitChangeRequestConfig.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useSaveOrgUnitChangeRequestConfiguration.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useCallbackOrgUnitConfigurationTypeDisplayName.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useOrgUnitConfigurationTypes.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useValidationSchemaOUCRC.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/configuration/types.ts
  hat/assets/js/cypress/fixtures/orgunits/changes/configuration/orgUnitChangeConfigurations.json
  hat/assets/js/cypress/integration/05 - orgUnits/changesConfiguration/changeRequestConfiguration.spec.js
  iaso/api/org_unit_change_request_configurations/filters.py
  iaso/api/org_unit_change_request_configurations/serializers.py
  iaso/api/org_unit_change_request_configurations/views.py
  iaso/api/org_unit_change_request_configurations/views_mobile.py
  iaso/api/query_params.py
  iaso/locale/fr/LC_MESSAGES/django.po
  iaso/migrations/0319_orgunitchangerequestconfiguration_type.py
  iaso/models/org_unit_change_request_configuration.py
  iaso/tests/api/org_unit_change_request_configurations/common_base_with_setup.py
  iaso/tests/api/org_unit_change_request_configurations/test_filters.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs.py
  iaso/tests/api/org_unit_change_request_configurations/test_org_unit_change_request_configs_mobile.py
  iaso/tests/models/test_org_unit_change_request_configuration.py
Labels: release, postrelease

#2067 IA-4076: OU patch dates
  iaso/api/org_units.py
  iaso/tests/api/test_orgunits.py
Labels: release

#2069 IA-3988 Differentiate Org Unit changes types (change request or not)
  Makefile
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/history/LogsDetails.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/history/messages.js
  hat/audit/admin.py
  hat/audit/migrations/0006_modification_org_unit_change_request.py
  hat/audit/models.py
  hat/audit/tests.py
  iaso/migrations/0002_auto_20191001_1142_squashed_0100_auto_20210702_0835.py
  iaso/migrations/0101_page_needs_authentication_squashed_0110_make_readonlyrole.py
  iaso/models/org_unit.py
  iaso/tests/models/test_org_unit_change_request.py
Labels: release

#2074 [IA-4105] Update make_translations comment format
  hat/locale/fr/LC_MESSAGES/django.po
  iaso/locale/fr/LC_MESSAGES/django.po
  iaso/management/commands/make_translations.py
  plugins/polio/locale/fr/LC_MESSAGES/django.po
  plugins/wfp/locale/fr/LC_MESSAGES/django.po
  plugins/wfp_auth/locale/fr/LC_MESSAGES/django.po
Labels: enhancement

#2072 IA-3750: QR Image link broken when no app id yet
  hat/assets/js/apps/Iaso/domains/projects/components/ProjectInfos.tsx
Labels: release

#2079 [IA-3940] Fix duplicated groups creation
  iaso/api/groups.py
  iaso/tests/api/test_groups.py
Labels: bug, release

#2047 POLIO-1871 Fix bug pdf upload on pre alerts
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/utils.tsx
  plugins/polio/tests/test_vaccine_supply_chain.py
Labels: release, postrelease

#2086 POLIO-1915: Country blocks bug
  plugins/polio/js/src/domains/Budget/BudgetFilters.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/CampaignsFilters.tsx
  plugins/polio/js/src/domains/VaccineModule/Nopv2Authorisations/Filters/Nopv2AuthorisationsFilters.tsx
  plugins/polio/js/src/domains/VaccineModule/Repository/forms/Filters.tsx
  plugins/polio/js/src/domains/VaccineModule/Repository/reports/Filters.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Filters/VaccineStockManagementFilters.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Filters/VaccineSupplyChainFilters.tsx
Labels: release

#2084 IA-4113 Avoid deleting shapes when performing a `PATCH` request on the org unit API
  iaso/api/org_units.py
  iaso/locale/fr/LC_MESSAGES/django.po
  iaso/tests/api/test_orgunits.py
Labels: release

#2093 [IA-4111] Fix update OrgUnits with default image
  hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitImages.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/types/orgUnit.ts
  iaso/api/org_units.py
  iaso/models/org_unit.py
  iaso/tests/api/test_orgunits.py
Labels: bug

#2112 POLIO-1921: block VRF creation for round w/o scope (front-end)
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/vrf.tsx
Labels: release

#2113 IA-4015: SETUPER: add planning data
  iaso/api/setup_account.py
  iaso/tests/api/test_setup_account.py
  setuper/data_collection.py
  setuper/micro_planning.py
Labels: release

#2117 IA-4145 change requests bulk approve filtering
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Components/MultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useBulkSaveChangeRequestStatus.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useGetApprovalProposals.ts
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
Labels: release

#2115 POLIO-1916: refresh button for VRF dashboard
  iaso/utils/powerbi.py
  plugins/polio/tests/test_refresh_powerbi.py
Labels: release

#2095 IA-4099: translations with module federations
  .gitignore
  docker-compose.yml
  docs/pages/dev/how_to/use_plugins/use_plugins.en.md
  docs/pages/dev/how_to/use_plugins/use_plugins.fr.md
  docs/pages/dev/how_to/use_tranlations/use_translations.en.md
  docs/pages/dev/how_to/use_tranlations/use_translations.fr.md
  docs/pages/dev/reference/env_variables/env_variables.en.md
  hat/assets/js/apps/Iaso/bundle/browserConfigs.js
  hat/assets/js/apps/Iaso/bundle/generators.js
  hat/assets/js/apps/Iaso/bundle/languages.js
  hat/assets/js/apps/Iaso/bundle/plugins.js
  hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.spec.js
  hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.tsx
  hat/assets/js/apps/Iaso/components/filters/DatesRange.js
  hat/assets/js/apps/Iaso/domains/app/components/LocalizedAppComponent.js
  hat/assets/js/apps/Iaso/domains/app/components/LocalizedAppComponent.tsx
  hat/assets/js/apps/Iaso/domains/app/constants.js
  hat/assets/js/apps/Iaso/domains/app/contexts/LocaleContext.tsx
  hat/assets/js/apps/Iaso/domains/app/translations/en.config.js
  hat/assets/js/apps/Iaso/domains/app/translations/es.config.js
  hat/assets/js/apps/Iaso/domains/app/translations/es.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.config.js
  hat/assets/js/apps/Iaso/domains/home/components/LangSwitch.tsx
  hat/assets/js/apps/Iaso/domains/instances/utils/utils.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersMultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/index.tsx
  hat/assets/js/apps/Iaso/plugins/hooks/types.d.ts
  hat/assets/js/apps/Iaso/plugins/hooks/usePlugins.ts
  hat/assets/js/apps/Iaso/types/IasoModules.d.ts
  hat/assets/js/apps/Iaso/utils/dates.ts
  hat/assets/js/apps/Iaso/utils/objectUtils.ts
  hat/assets/js/cypress/integration/03 - Users/list.spec.js
  hat/assets/js/test/dom.js
  hat/assets/js/test/helpers.js
  hat/common/context_processors.py
  hat/settings.py
  hat/templates/iaso/index.html
  hat/webpack.dev.js
  hat/webpack.prod.js
  plugins/polio/js/src/domains/Config/ReasonsForDelay/CreateEdit/CreateEditReasonForDelay.tsx
  plugins/polio/js/src/domains/Config/ReasonsForDelay/hooks/columns.tsx
  plugins/polio/js/src/domains/Config/ReasonsForDelay/hooks/validation.tsx
Labels: postrelease

#2106 IA-4126: update blsq-comp
  package-lock.json
  package.json
Labels: postrelease

#2123 [IA-4146] Fix filters on Instance bulk actions
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceReferenceSubmission/LinkReferenceInstancesComponent.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/PushInstanceGps/PushGpsDialogComponent.tsx
  hat/assets/js/apps/Iaso/domains/instances/hooks/useInstanceBulkgpspush.tsx
  hat/assets/js/apps/Iaso/domains/instances/hooks/useReferenceInstanceBulkLink.tsx
  hat/assets/js/apps/Iaso/domains/instances/utils/index.tsx
  iaso/api/export_requests.py
  iaso/api/instances/__init__.py
  iaso/api/instances/instance_filters.py
  iaso/api/instances/instances.py
  iaso/api/storage.py
  iaso/api/tasks/create/instance_bulk_gps_push.py
  iaso/api/tasks/create/instance_reference_bulk_link.py
  iaso/management/commands/reimport_failed_imports.py
  iaso/models/base.py
  iaso/tasks/instance_bulk_gps_push.py
  iaso/tasks/instance_reference_bulk_link.py
  iaso/tasks/process_mobile_bulk_upload.py
  iaso/tests/api/instances/__init__.py
  iaso/tests/api/instances/test_instances.py
  iaso/tests/tasks/test_instance_bulk_gps_push.py
  iaso/tests/tasks/test_process_mobile_bulk_upload.py
  iaso/tests/tasks/test_reference_instance_bulk_link.py
  iaso/urls.py
  plugins/registry/api/registry.py
Labels: bug

#2130 IA-4159 Implement a slightly more verbose `validate_precision` method
  iaso/api/common.py
  iaso/api/org_unit_change_requests/serializers.py
  iaso/tests/utils/test_rounded_decimal_field.py
  iaso/utils/serializer/rounded_decimal_field.py
Labels: enhancement

#2126 [IA-4159] Round accuracy when there are more than 2 decimal places
  iaso/api/org_unit_change_requests/serializers.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/utils/test_rounded_decimal_field.py
  iaso/utils/serializer/rounded_decimal_field.py
Labels: enhancement

#2135 Cypress errors and datetime Cell is wrong
  hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.spec.js
  hat/assets/js/apps/Iaso/components/Cells/DateTimeCell.tsx
  hat/assets/js/cypress/integration/01 - auth/login.spec.js
  hat/assets/js/cypress/integration/05 - orgUnits/reviewChanges/changeRequest.spec.js
  hat/assets/js/cypress/integration/09 - projects/list.spec.js
Labels: release

#2116 IA-4135 IA-4161 instance translations missing
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContent.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContent.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentBasic.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentBasic.tsx
  hat/assets/js/apps/Iaso/domains/instances/components/InstanceFileContentRich.tsx
  hat/assets/js/apps/Iaso/domains/registry/components/selectedOrgUnit/index.tsx
Labels: release

#2134 IA-4117 Fix org unit with an empty `source_ref` causes the synchronization to fail
  iaso/diffing/synchronizer.py
  iaso/tests/api/data_source_versions_synchronization/test_views.py
  iaso/tests/models/test_data_source_versions_synchronization.py
Labels: release
