Repository BLSQ/iaso, pull requests merged in 2025-05, with the labels that each got.

#2081 POLIO-1863 Vaccine management add third permission read only
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/users/permissionsMessages.ts
  hat/assets/js/apps/Iaso/utils/permissions.ts
  hat/locale/fr/LC_MESSAGES/django.po
  hat/menupermissions/constants.py
  hat/menupermissions/migrations/0072_alter_custompermissionsupport_options.py
  hat/menupermissions/models.py
  iaso/locale/fr/LC_MESSAGES/django.po
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/api/vaccines/permissions.py
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/api/vaccines/supply_chain.py
  plugins/polio/js/src/constants/permissions.ts
  plugins/polio/js/src/constants/routes.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/PreAlerts/PreAlerts.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VAR/VaccineArrivalReports.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/shared.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Table/useVaccineSupplyChainTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/VaccineSupplyChain.tsx
  plugins/polio/tests/test_vaccine_stock_earmarked.py
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#2146 IA-4171 Org Unit Type restrictions shouldn't be used in user creation/modification
  iaso/api/profiles/bulk_create_users.py
  iaso/api/profiles/profiles.py
  iaso/tasks/profiles_bulk_update.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_profiles_bulk_update.py
  iaso/tests/test_create_users_from_csv.py
Labels: release

#2147 IA-4186: exclude hidden path from redirections
  hat/assets/js/apps/Iaso/domains/users/utils.js
Labels: release

#2149 [IA-4188] Fixed module federation files generation
  hat/assets/js/apps/Iaso/bundle/generators.js
  hat/webpack.dev.js
Labels: bug

#2162 [IA-3775, IA-4110, IA-4207] Add new feature flags
  iaso/migrations/0324_auto_20250514_1244.py
Labels: enhancement

#2160 POLIO-1875 Add Created At column to differentiate if multiple VRFs
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Table/useVaccineSupplyChainTableColumns.tsx
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/messages.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/types.ts
Labels: release

#2164 [IA-4148] Fix PaymentLot creation select_all
  hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useGetPotentialPayments.tsx
  hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useGetSelectedPotentialPayments.tsx
Labels: bug, release

#2161 IA-4178 Users admin can bypass project restrictions in users management
  hat/assets/js/apps/Iaso/domains/projects/hooks/requests.ts
  hat/assets/js/apps/Iaso/domains/users/components/Filters.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersMultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/users/config.js
  hat/assets/js/apps/Iaso/domains/users/index.tsx
  iaso/api/profiles/bulk_create_users.py
  iaso/api/profiles/profiles.py
  iaso/api/projects/viewsets.py
  iaso/tests/api/test_profiles.py
  iaso/tests/api/test_projects.py
  iaso/tests/fixtures/test_user_bulk_create_managed_geo_limit.csv
  iaso/tests/test_create_users_from_csv.py
Labels: release
