Repository BLSQ/iaso, pull requests merged in 2025-03, with the labels that each got.

#1998 POLIO-1861 Fix cannot create VRF bug
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/Details/VaccineRequestForm/VaccineRequestForm.tsx
Labels: release

#1990 IA-3733: Handle bulk approve and bulk reject of change requests (frontend)
  hat/assets/js/apps/Iaso/domains/app/translations/en.json
  hat/assets/js/apps/Iaso/domains/app/translations/fr.json
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Components/MultiActionsDialog.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useBulkSaveChangeRequestStatus.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/api/useGetApprovalProposals.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/index.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/messages.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/types.ts
  iaso/api/org_unit_change_requests/serializers.py
  iaso/api/org_unit_change_requests/views.py
  iaso/tasks/org_unit_change_requests_bulk_review.py
  iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
  iaso/tests/api/org_unit_change_requests/test_serializers.py
Labels: postrelease

#2002 POLIO-1855: prevent region scope selection to add invalid org units
  plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
  plugins/polio/js/src/domains/Campaigns/Scope/ScopeInput.tsx
  plugins/polio/js/src/domains/Campaigns/Scope/hooks/useGetGeoJson.ts
Labels: release

#2000 IA-3959: Review changes page: add column "Payment status" only if module "Payment" is activated
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Filter/ReviewOrgUnitChangesFilter.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/Tables/ReviewOrgUnitChangesTable.tsx
  hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/constants.ts
  hat/assets/js/apps/Iaso/utils/usersUtils.ts
  iaso/models/base.py
Labels: release

#1983 POLIO-1776: subactivity validation
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/api/campaigns/subactivities.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/Campaigns/MainDialog/CreateEditDialog.tsx
  plugins/polio/js/src/domains/Campaigns/MainDialog/usePolioDialogTabs.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/components/Modal/CreateEditSubActivity.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/hooks/useSubActivityValidation.tsx
  plugins/polio/js/src/domains/Campaigns/SubActivities/messages.ts
  plugins/polio/js/src/domains/Campaigns/SubActivities/types.ts
  plugins/polio/js/src/domains/Campaigns/hooks/api/useSaveCampaign.ts
  plugins/polio/models/base.py
  plugins/polio/services/campaign.py
  plugins/polio/tests/api/campaigns/test_campaigns_1.py
Labels: release

#2015 IA-4024: Fix Cypress test
  hat/assets/js/cypress/fixtures/profiles/me/superuser.json
  hat/assets/js/cypress/integration/05 - orgUnits/list.spec.js
Labels: release

#2005 IA-3996: Group filter doesn't seem to work on OU list
  iaso/api/org_unit_search.py
  iaso/tests/api/test_orgunits.py
Labels: release

#2006 IA-3871: Add hyperlink to Org Unit from submission
  hat/assets/js/apps/Iaso/domains/instances/components/ActionTableColumnComponent.js
  hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
  hat/assets/js/apps/Iaso/domains/instances/constants.js
Labels: release

#2013 IA-3566: product fruit integration
  docker-compose.yml
  docs/pages/dev/reference/env_variables/env_variables.en.md
  hat/assets/js/apps/Iaso/domains/app/components/ProductFruits.tsx
  hat/assets/js/apps/Iaso/domains/app/index.tsx
  hat/assets/js/apps/Iaso/index.tsx
  hat/assets/js/apps/Iaso/utils/usersUtils.ts
  hat/common/context_processors.py
  hat/settings.py
  hat/templates/iaso/index.html
  package-lock.json
  package.json
Labels: release

#2003 IA-3980 Earmarked stocks make campaign and round selection not mandatory
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/Summary/VaccineStockManagementSummary.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Details/VaccineStockManagementDetails.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditEarmarked.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/validation.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/messages.ts
  plugins/polio/migrations/0224_earmarkedstock_temporary_campaign_name_and_more.py
  plugins/polio/models/base.py
  plugins/polio/tests/test_vaccine_stock_earmarked.py
  plugins/polio/tests/test_vaccine_stock_management.py
Labels: release

#2009 IA-4008: OrgUnit - Tab "Map" - All choices are invisibles
  package-lock.json
Labels: release

#2017 IA-4022: Instance upload bug with same OrgUnit UUID
  iaso/api/instances.py
  iaso/tests/api/test_instances.py
Labels: bug, release

#2026 [IA-4034] Workflow copy error - name too long
  iaso/api/workflows/utils.py
  iaso/models/workflow.py
  iaso/tests/api/workflows/test_workflows.py
Labels: bug

#2043 Polio 1870 split test and on hold campaigns
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/api/chronogram/views.py
  plugins/polio/budget/api.py
  plugins/polio/js/src/components/Inputs/BooleanInput.js
  plugins/polio/js/src/constants/messages.ts
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/types.ts
  plugins/polio/js/src/constants/urls.ts
  plugins/polio/js/src/domains/Calendar/Calendar.tsx
  plugins/polio/js/src/domains/Calendar/ExportCsvModal.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/Body.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/CampaignsFilters.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/IsOnHoldLegend.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/RoundCell.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/index.tsx
  plugins/polio/js/src/domains/Calendar/campaignCalendar/types.ts
  plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
  plugins/polio/js/src/domains/Campaigns/BaseInfo/BaseInfoForm.tsx
  plugins/polio/js/src/domains/Campaigns/CampaignsList/Dashboard.tsx
  plugins/polio/js/src/domains/Campaigns/CampaignsList/useCampaignsTableColumns.tsx
  plugins/polio/js/src/domains/Campaigns/hooks/api/useGetCampaigns.ts
  plugins/polio/js/src/domains/Campaigns/hooks/useCampaignCategoryOptions.ts
  plugins/polio/js/src/domains/GroupedCampaigns/GroupedCampaignDialog.tsx
  plugins/polio/js/src/domains/LQAS-IM/IM/index.js
  plugins/polio/js/src/domains/LQAS-IM/LQAS/index.js
  plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditFormA.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/Table/VaccineStockManagementTable.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/api.ts
  plugins/polio/js/src/domains/VaccineModule/SupplyChain/hooks/api/vrf.tsx
  plugins/polio/js/src/hooks/useFormValidator.js
  plugins/polio/migrations/0225_campaign_on_hold.py
  plugins/polio/models/base.py
  plugins/polio/tests/api/campaigns/test_campaigns_2.py
  plugins/polio/tests/api/campaigns/test_campaigns_csv.py
Labels: release

#2029 IA-3722: SETUPER: Run a duplicates entity analysis at the launch of demo account
  setuper/entities.py
Labels: release

#2019 WC2-683: Add ETL guide
  docs/pages/users/how_to/run_ETL/attachments/Add-periodical-task-Button.png
  docs/pages/users/how_to/run_ETL/attachments/Beneficiary.png
  docs/pages/users/how_to/run_ETL/attachments/Journey.png
  docs/pages/users/how_to/run_ETL/attachments/Monthly-statistics.png
  docs/pages/users/how_to/run_ETL/attachments/Periodic-Tasks.png
  docs/pages/users/how_to/run_ETL/attachments/Periodic-task-Iaso-Form.png
  docs/pages/users/how_to/run_ETL/attachments/Periodic-task-List.png
  docs/pages/users/how_to/run_ETL/attachments/Run-periodic-task.png
  docs/pages/users/how_to/run_ETL/attachments/Select-periodic-task-to-run.png
  docs/pages/users/how_to/run_ETL/attachments/Steps.png
  docs/pages/users/how_to/run_ETL/attachments/Task-results-list.png
  docs/pages/users/how_to/run_ETL/attachments/Visits.png
  docs/pages/users/how_to/run_ETL/run_ETL.md
Labels: release

#2050 POLIO-1876: fix campaign filter
  plugins/polio/api/campaigns/campaigns.py
  plugins/polio/models/base.py
  plugins/polio/tests/models/test_round_models.py
Labels: release

#2048 POLIO-1864: embed stock export
  hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetGroups.ts
  hat/assets/js/apps/Iaso/hooks/useFilterState.ts
  hat/assets/js/apps/Iaso/hooks/useTabs.tsx
  hat/assets/js/apps/Iaso/index.tsx
  hat/dashboard/urls.py
  iaso/api/groups.py
  plugins/polio/api/dashboards/supply_chain.py
  plugins/polio/api/urls.py
  plugins/polio/api/vaccines/export_utils.py
  plugins/polio/api/vaccines/public_vaccine_stock.py
  plugins/polio/api/vaccines/stock_management.py
  plugins/polio/js/src/constants/menu.tsx
  plugins/polio/js/src/constants/routes.tsx
  plugins/polio/js/src/constants/translations/en.json
  plugins/polio/js/src/constants/translations/fr.json
  plugins/polio/js/src/constants/urls.ts
  plugins/polio/js/src/domains/VaccineModule/Repository/VaccineRepository.tsx
  plugins/polio/js/src/domains/VaccineModule/Repository/forms/index.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/PublicVaccineStock.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/Filters.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/FormControl.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/LanguageButton.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/SingleSelect.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/TabSwitchButton.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/Table.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/TextInput.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/VialsSummary.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/components/utils.tsx
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/messages.ts
  plugins/polio/js/src/domains/VaccineModule/StockManagement/PublicPage/useGetPublicVaccineStock.tsx
  plugins/polio/models/base.py
  plugins/polio/tasks/archive_vaccine_stock_for_rounds.py
Labels: release
