Repository BLSQ/iaso, pull requests merged in 2025-08, with the labels that each got.

#2354 [IA-4414] Allow multiple models in plugin permissions
  hat/menupermissions/models.py
  iaso/permissions.py
  iaso/test.py
  plugins/polio/permissions.py
Labels: enhancement

#2357 [IA-4416] Add utility functions is_plugin_active
  iaso/api/logs.py
  iaso/api/org_units.py
  iaso/plugins.py
Labels: enhancement, release

#2353 POLIO-1983: Add LQAS models
  iaso/models/org_unit.py
  plugins/polio/api/lqas_im/lqas_data_manager.py
  plugins/polio/api/lqas_im/lqas_im_datastore.py
  plugins/polio/locale/fr/LC_MESSAGES/django.po
  plugins/polio/management/commands/convert_data_stores_to_lqas.py
  plugins/polio/management/commands/convert_json_to_lqas.py
  plugins/polio/migrations/0238_lqasrounddata_lqasdistrictdata_and_more.py
  plugins/polio/models/__init__.py
  plugins/polio/models/lqas_im.py
  plugins/polio/tests/models/test_lqas_district_data.py
  plugins/polio/tests/models/test_lqas_round_data.py
  plugins/polio/tests/test_lqas_data_manager.py
Labels: release

#2176 IA-4248: remove Enzyme, update eslint
  .eslintrc.json
  .prettierrc
  eslint.config.mjs
  hat/assets/js/apps/Iaso/components/forms/Checkboxes.spec.js
  hat/assets/js/apps/Iaso/components/forms/EditableTextFields.spec.js
  hat/assets/js/apps/Iaso/domains/app/index.spec.js
  hat/assets/js/apps/Iaso/domains/forms/components/FormVersionsDialogComponent.spec.js
  hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
  hat/assets/js/cypress/fixtures/forms/test-form.xlsx
  hat/assets/js/cypress/integration/02 - forms/form-versions-dialog.spec.js
  hat/assets/js/cypress/support/index.js
  hat/assets/js/test/helpers.js
  package-lock.json
  package.json
  pyproject.toml
Labels: postrelease

#2306 POLIO-1948: azure storage
  docs/Azure-Storage-Configuration.md
  docs/pages/dev/reference/env_variables/env_variables.en.md
  hat/settings.py
  iaso/storage.py
  requirements.txt
  scripts/test_azure_storage.py
Labels: postrelease

#2360 IA-4417: upgrade to node 22.18.0 and npm 10.9.3
  .github/workflows/cypress.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e_tests_staging.yml
  .github/workflows/main.yml
  azure-pipelines-prod.yml
  azure-pipelines.yml
  docker/bundle/Dockerfile
  docker/webpack/Dockerfile
  hat/assets/js/apps/Iaso/components/files/pdf/PdfPreview.tsx
  hat/assets/js/cypress/README.md
  hat/assets/js/test/dom.js
  package-lock.json
  package.json
Labels: postrelease

#2363 [IA-3686] Export Groups in csv/xlsx
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/constants.js
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/hooks/usePrepareGroupExportUrls.ts
  hat/assets/js/apps/Iaso/domains/orgUnits/groups/index.js
  iaso/api/groups/__init__.py
  iaso/api/groups/filters.py
  iaso/api/groups/serializers.py
  iaso/api/groups/views.py
  iaso/locale/fr/LC_MESSAGES/django.po
  iaso/test.py
  iaso/tests/api/groups/__init__.py
  iaso/tests/api/groups/test_filters.py
  iaso/tests/api/groups/test_serializers.py
  iaso/tests/api/groups/test_views.py
  iaso/urls.py
Labels: enhancement

#2364 [IA-4418] Fix migration 0337
  iaso/migrations/0337_featureflag_category_featureflag_is_dangerous_and_more.py
Labels: bug

#2383 [IA-4141] Fix file paths in local setup
  README.md
  iaso/api/forms.py
  iaso/api/instances/instances.py
  iaso/api/instances/views_mobile.py
  iaso/api/mobile/org_units.py
  iaso/management/commands/seed_test_data.py
  iaso/models/base.py
  iaso/models/forms.py
  iaso/tests/api/test_mobile_orgunits.py
Labels: enhancement, release

#2274 [IA-3801] Fix auto-OUCR creates invalid OUCR
  iaso/api/instances/instances.py
  iaso/models/org_unit.py
  iaso/tests/models/test_org_unit_change_request.py
Labels: bug
